ALTER ROLE [db_owner] ADD MEMBER [CYMRU\Ke068888]
GO
ALTER ROLE [db_owner] ADD MEMBER [CYMRU\Ma075603]
GO
ALTER ROLE [db_owner] ADD MEMBER [CYMRU\mi140036]
GO
ALTER ROLE [db_owner] ADD MEMBER [CYMRU\SVC072083]
GO
ALTER ROLE [db_owner] ADD MEMBER [CYMRU\SVC192487]
GO
ALTER ROLE [db_owner] ADD MEMBER [DWFTReader]
GO
ALTER ROLE [db_owner] ADD MEMBER [PLUSER]
GO
