SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[Get_Covid_Data_WPAS_Central_Live] AS BEGIN

SELECT
	'Central' AS Area,
	'WPAS' AS Source,
	CASENO AS LocalPatientIdentifer,
	NHS AS NHSNumber,
	RTRIM(SURNAME) AS Surname,
	RTRIM(FORENAME) AS Forename,
	CAST(BIRTHDATE AS DATE) AS DateOfBirth,
	SEX AS Sex,
	CAST(TRT_DATE AS DATETIME) + CAST(CAST(STUFF(APPOINTMENT_TIME,3,0,':') AS TIME) AS DATETIME) AS AdmissionDateTime,
	CLOC AS Ward,
	CCONS AS LocalConsultantCode,
	CSPEC AS Specialty,
	BELONGS_TO AS Site







FROM(
SELECT * FROM OPENQUERY(WPAS_CENTRAL,
'
Select 
	PATIENT.CASENO,
	PATIENT.NHS,
	PATIENT.FORENAME,
	PATIENT.SURNAME,
	PATIENT.BIRTHDATE,
	PATIENT.SEX,
	PATIENT.POSTCODE,
	PATIENT.Registered_GP,
	PATIENT.GP_Practice,
	MASTER_TRT.TRT_DATE,
	MASTER_TRT.APPOINTMENT_TIME,
	'''' AS RetentionReason,
	MASTER_TRT.CLOC ,
	GP2.GP_CODE ,
	MASTER_TRT.CCONS ,
	MASTER_TRT.CSPEC,
	PADLOC.BELONGS_TO,
	PADLOC.BASE_DESC
from 
	MASTER_TRT 
	LEFT join PATIENT on MASTER_TRT.CASENO = PATIENT.CASENO 
	LEFT join PADLOC on MASTER_TRT.CLOC = PADLOC.LOCCODE
	LEFT join GP2 on MASTER_TRT.CCONS = GP2.PRACTICE
where 
	MASTER_TRT.TRT_TYPE IN (''AC'',''AL'',''AE'')
'
)
)InpatientAdmissions

UNION ALL

SELECT
	'East' AS Area,
	'Myrddin' AS Source,
	CASENO AS LocalPatientIdentifier,
	NHS AS NHSNumber,
	RTRIM(SURNAME) AS Surname,
	RTRIM(FORENAME) AS Forename,
	CAST(BIRTHDATE AS DATE) AS DateOfBirth,
	SEX AS Sex,
	CAST(TRT_DATE AS DATETIME) + CAST(CAST(STUFF(APPOINTMENT_TIME,3,0,':') AS TIME) AS DATETIME)  AS AdmissionDate,
	CLOC AS Ward,
	CCONS AS LocalConsultantCode,
	CSPEC AS Specialty,
	BELONGS_TO AS Site

FROM(
SELECT * FROM OPENQUERY(WPAS_EAST,
'
Select 
	PATIENT.CASENO,
	PATIENT.NHS,
	PATIENT.FORENAME,
	PATIENT.SURNAME,
	PATIENT.BIRTHDATE,
	PATIENT.SEX,
	PATIENT.POSTCODE,
	PATIENT.Registered_GP,
	PATIENT.GP_Practice,
	MASTER_TRT.TRT_DATE,
	'''' AS RetentionReason,
	MASTER_TRT.CLOC ,
	PADLOC.LOCDESC ,
	GP2.GP_CODE ,
	MASTER_TRT.CCONS ,
	MASTER_TRT.CSPEC,
	PADLOC.BELONGS_TO,
		PADLOC.BASE_DESC,
	MASTER_TRT.ACTNOTEKEY,
	MASTER_TRT.TRT_INTENT,
	MASTER_TRT.ADMIT_METHOD,
	'''' AS HomeLeave,
   MASTER_TRT.LINKID AS LinkId,
   RTRIM(MASTER_TRT.REAL_MANAGEMENT) AS PatientClassification,
	MASTER_TRT.APPOINTMENT_TIME,
	MASTER_TRT.SOURCE AS AdmissionSource
from 
	MASTER_TRT 
	LEFT join PATIENT on MASTER_TRT.CASENO = PATIENT.CASENO 
	LEFT join PADLOC on MASTER_TRT.CLOC = PADLOC.LOCCODE
	LEFT join GP2 on MASTER_TRT.CCONS = GP2.PRACTICE
where 
	MASTER_TRT.TRT_TYPE IN (''AC'',''AL'',''AE'')
')
)InpatientAdmissions	

END
GO
