SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



-- =============================================
-- Author:		Heather Lewis                         
-- Create date: 6/10/2020
-- Description:	Centre - Extract of all Waiters (OP/DC/IP/FU/PP)
--              This version created to fix error "Unable to Execute an Execute"
--              Data succesfully loads into foundation   
--  Amend Date: 12/01/2021 x4 new fields added
--              22/06/2021 Risk Stratification fields not in Wpas SP
--              
-- =============================================


CREATE PROCEDURE [dbo].[Get_PAS_Data_Waiters_Centralv222]
	
AS
BEGIN
	
	SET NOCOUNT ON;
	
declare @sql as varchar(max)
declare @today as datetime
declare @TodayDateText as varchar(20)

set @today = getdate()
set @TodayDateText = datename(day, @today) + ' ' + datename(month, @today) + ' ' + datename(year, @today)

DECLARE @LastDateWaitingListCensus AS DATE = (SELECT ISNULL(MAX(DateWaitingListCensus),'01 January 2018') FROM [Foundation].[dbo].[PAS_Data_WaitingList] where Area='Central')
DECLARE @LastDateWaitingListCensusString AS VARCHAR(30) = DATENAME(DAY,@LastDateWaitingListCensus) + ' ' + DATENAME(MONTH,@LastDateWaitingListCensus) + ' ' + DATENAME(YEAR,@LastDateWaitingListCensus)

EXEC('

Select distinct

wl.LOS as DaysWait,
wl.NHS as NHSNumber,
wl.CaseNo as LocalPatientIdentifier,
wl.dat_ref as DateReferred,
wl.LinkID as SystemLinkID,
wl.INTENT_REFER AS ReferralIntent,
wl.GP_REF as Referrer,
wl.GP_PRAC AS ReferringOrganisation,
wl.Reg_GP as GPAtTimeOfActivity,
wl.Reg_Prac as GPPracticeAtTimeOfActivity,
wl.Postcode as PostcodeAtTimeOfActivity,
wl.DHA_CODE as Commissioner,
wl.Source_Refer as ReferralSource,
wl.LTTR_PRTY AS PriorityOnLetter,
wl.Ref_Outcome as Outcome,
wl.Datonsys as DateOnWaitingList,
wl.Loc as Location,
wl.Category as PatientCategory,
wl.Cons_Prty as PriorityOfHCP,
wl.trt_type as TreatmentType,
wl.Date_Booked as DateBooked,
wl.Reason_Booked as ReasonBooked,
wl.GPREFNO as GpRefNo,
wl.Clinical_Condition as ClinicalCondition,
wl.Charged_To as CommissionerType,
wl.TRT_DATE as DateOfAppointment, 
wl.Deferred_Date as DateDeferred,
wl.Spec as Specialty,
wl.List_Outcome as ListStatus,    
wl.Contracts_Authorised as ContractsAuthorised,  
wl.origtext as Comments,
wl.AgeInDays as AgeInDays,
wl.Suspended as Suspended, 
wl.Orig_Diag_description as OriginalDiagnosis,
wl.Exclude_PPO1W as ExcludeFromWLReporting,
wl.ACTNOTEKEY as ActNoteKey,
wl.RTT_UPI as UniquePathwayIdentifier,
wl.RTT_Start_Date as DateRTTStart,
wl.RTT_Stop_Date as DateRTTStop,
wl.RTT_LOW AS RTTWait,
wl.RTT_Adjusted_LOW as RTTWaitAdjusted,
wl.RTT_Spec AS RTTSpecialty,
wl.RTT_ACTNOTEKEY_Start as RTTActNotekeyAtStart,
wl.RTT_Exclude AS RTTExcludedSpecialty,
wl.Planned_OP_Date as DatePlanned,
wl.RTT_Start_Source as RTTSourceAtStart,
wl.RTT_Start_Type as RTTTypeAtStart,
wl.RTT_Target_Date as DateRTTTarget,
wl.RTT_TARGET AS RTTTargetDays,
wl.Pathway_Stage  as RTTStage,
NULL as DateOfLastDNAOrPatientCancelled,
NULL as CommentsFromWaitingList,
NULL as WaitingListRefNo,
NULL as ScheduleRefNo,
NULL as ReferralRefNo,
C.THECODE as OPCS,
NULL as ProcedureProposed,
GP2.GP_CODE as HCP,
wl.TARGET_DATE as DateOfOriginalTarget,
cast(''Now'' as Date) as DateWaitingListCensus,
r.pref_ward as BookedWardOrClinic,
NULL as CommentsOfReferral,
NULL as TimeEstimatedInTheatre,
--wl.Anaesthetic_Type as AnaestheticType,
r.ref_anaes_type as AnaestheticType,
''Central'' as Area,
''Wpas'' as Source,
wl.HEALTH_RISK_FACTOR as HealthRiskFactor,
wl.WEIGHTED_PR_F as WeightedPRF,
wl.PERCENTAGE_OVERRUN as PercentageOverRun,  
wl.ARMED_SERVICES_KEYNOTE as ArmedServicesKeyNote,
padloc.provider_code as Site,
--wl.Theatre_Type as TheatreType,  
r.thr_type as TheatreType,
r.datonsys as DateOnSystem,
wl.APPT_DIR_DESC as AppointmentDirective,
wl.Adjusted_Days as DaysAdjusted,
wl.Session_Key as ClinicSessionKey,
wl.NEXT_APPT_DATE as DateNextAppointment,
wl.LAST_EVENT_DATE as DateLastEvent,
wl.LAST_EVENT_CODE as LastEvent,
wl.LAST_EVENT_CONS as HCPLastEvent,
wl.LAST_EVENT_SPEC as SpecialtyLastEvent,
--wl.LAST_ACT_OUTCOME as LastActOutcome,
O3.OUTCOME_CODE as LastActivityOutcome,
--wl.LAST_ACT_TYPE as LastActType,
CASE WHEN TT.TRt_type is null  then OU.OUTCOME_CODE ELSE TT.TRt_type END as LastActivityType,
wl.LAST_EVENT_LOC as LastEventLoc,
wl.FU_ACTNOTEKEY as ActNotekeyFU,
wl.FU_TO_COME_IN_DATE as DateFUToComeIn,
wl.PLANNED_ASA_GRADE as PlannedASAGrade,
--wl.INTENDED_ADMIT_METHOD as IntendedAdmitMethod,
m2.method as AdmissionMethodIntended,
--wl.wLIST AS WaitingListType,
''OP'' as WaitingListType, 
wl.DOC_REFERENCE_NO AS DocumentReference,
wl.VIRTUAL_TYPE as VirtualType,
wl.CONSULT_METHOD as ConsultMethod,
wl.PREVIOUS_VIRTUAL_TYPE as PreviousVirtualType,
wl.PREVIOUS_CONSULT_METHOD as PreviousConsultMethod,
wl.PREF_VIRTUAL_TYPE as PreferredVirtualType,
wl.PREF_CONSULT_METHOD as PreferredConsultMethod,
wl.VIRTUAL_CONTACT_DETAILS as VirtualContactDetail,
wl.ELECTIVE_PRIORITY_LEVEL as ElectivePriorityLevel,
wl.REPRIORITISED_TAGET_DATE as DateReprioritisedTarget,
wl.ADMIT_METHOD AS AdmissionMethodRePrioritised,
cast(pathway_notes as varchar (3000)) as PathwayNote,
Null as DaysSuspension,
Null as DaysDNASuspension,
Null as DateDNA,
Null as DateLastPreOp,
Null as LastPreOpAttendanceStatus,
Null as DateConsultantChangeRefused,
Null as ListReviewStatus,
Null as TotalAdmissionOffers,
Null as DateAppointmentRescheduled,
Null as IntendedManagement,
Null as DateReferralRequestReceived,
Null as DateReferralSent,
Null as ReferralReason,
Null as LocalReferralUrgnc,
Null as LocalReferralPrity,
Null as DateLastSuspensionStart,
Null as DateLastSuspensionEnd,
Null as LastSuspensionReason,
Null as DateLastWaitingListReview,
Null as LastWaitingListReviewStatus,
Null as LastWaitingListReviewBatchNumber,
Null as EisQueryId,
Null as ElectiveAdmissionType,
Null as LocalWLType,
rep.priority_by as HCPRePrioritisedBy,
rep.priority_date as DateRePrioritised,
Null as PriorityClinical,
wl.DISCHARGE_DATE as DateDischargeOfLastAdmission,
wl.NEXT_APPT_NEEDED as NextApptNeeded,
null as DateDDTA

/*
r.CLIN_REF_DATE as ClinicalReferralDate,
TT.TRT_TYPE as TRT_TYPE2, 
ou.OUTCOME_CODE AS outcome_code2,
*/

	from 
	
		REF_WAIT_LEN_VIEW_ENH (''21'',''' + @TodayDateText + ''','''','''','''','''') as wl
		left join Refer R on WL.LinkID = R.LINKID
		left join coding c on c.linkid = wl.linkid and((c.itemno=1) or (c.itemno is null)) and c.when_coded = ''4'' and code_type =''OP''
		left join padloc on wl.loc = padloc.loccode
		left join GP2 on r.cons = gp2.practice
		left join TRT_TYPE TT ON TT.trt_DESCRIPTION = wl.LAST_act_type 
        left join OUTCOME OU ON OU.DESCRIPT = wl.LAST_act_type
		left join OUTCOME O3 ON O3.DESCRIPT = wl.LAST_act_OUTCOME
		left join ADMITMTH m2 on m2.description = wl.INTENDED_ADMIT_METHOD
		left join PATHWAYMGT pm ON pm.UPI = wl.RTT_UPI and (coalesce (pm.event_Source, ''PN'') = ''PN'' and pm.pwaykey = (select first 1 pm2.pwaykey from pathwaymgt pm2 where pm2.UPI = wl.RTT_UPI and coalesce(pm2.event_source, ''PN'') = ''PN''))
		left join REF_ELECTIVE_REPRIORITISED rep on rep.seqno = (select first 1 seqno from REF_ELECTIVE_REPRIORITISED r2 where r2.linkid = wl.linkid order by date_entered desc) 



union

Select distinct

wl.LOS AS DaysWait,
wl.NHS AS NHSNumber,
wl.CaseNo as LocalPatientIdentifier,
wl.dat_ref as DateReferred,
wl.LinkID as SystemLinkID,
wl.INTENT_REFER AS ReferralIntent,
wl.GP_REF as Referrer,
wl.GP_PRAC AS ReferringOrganisation,
wl.Reg_GP as GPAtTimeOfActivity,
wl.Reg_Prac as GPPracticeAtTimeOfActivity,
wl.Postcode as PostcodeAtTimeOfActivity,
wl.DHA_CODE as Commissioner,
wl.Source_Refer as ReferralSource,
wl.LTTR_PRTY AS PriorityOnLetter,
wl.Ref_Outcome as Outcome,
wl.Datonsys as DateOnWaitingList,
wl.Loc as Location,
wl.Category as PatientCategory,
wl.Cons_Prty as PriorityOfHCP,
wl.trt_type as TreatmentType,
wl.Date_Booked as DateBooked,
wl.Reason_Booked as ReasonBooked,
wl.GPREFNO as GpRefNo,
wl.Clinical_Condition as ClinicalCondition,
wl.Charged_To as CommissionerType,
wl.TRT_DATE as DateOfAppointment, 
wl.Deferred_Date as DateDeferred,
wl.Spec as Specialty,
wl.List_Outcome as ListStatus,    
wl.Contracts_Authorised as ContractsAuthorised,  
wl.origtext as Comments,
wl.AgeInDays as AgeInDays,
wl.Suspended as Suspended, 
wl.Orig_Diag_description as OriginalDiagnosis,
wl.Exclude_PPO1W as ExcludeFromWLReporting,
wl.ACTNOTEKEY as ActNoteKey,
wl.RTT_UPI as UniquePathwayIdentifier,
wl.RTT_Start_Date as DateRTTStart,
wl.RTT_Stop_Date as DateRTTStop,
wl.RTT_LOW AS RTTWait,
wl.RTT_Adjusted_LOW as RTTWaitAdjusted,
wl.RTT_Spec AS RTTSpecialty,
wl.RTT_ACTNOTEKEY_Start as RTTActNotekeyAtStart,
wl.RTT_Exclude AS RTTExcludedSpecialty,
wl.Planned_OP_Date as DatePlanned,
wl.RTT_Start_Source as RTTSourceAtStart,
wl.RTT_Start_Type as RTTTypeAtStart,
wl.RTT_Target_Date as DateRTTTarget,
wl.RTT_TARGET AS RTTTargetDays,
wl.Pathway_Stage  as RTTStage,
NULL as DateOfLastDNAOrPatientCancelled,
NULL as CommentsFromWaitingList,
NULL as WaitingListRefNo,
NULL as ScheduleRefNo,
NULL as ReferralRefNo,
c.THECODE as OPCS,
NULL as ProcedureProposed,
GP2.GP_CODE as HCP,
wl.TARGET_DATE as DateOfOriginalTarget,
cast(''Now'' as Date) as DateWaitingListCensus,
r.pref_ward as BookedWardOrClinic,
NULL as CommentsOfReferral,
NULL as TimeEstimatedInTheatre,
--wl.Anaesthetic_Type as AnaestheticType,
r.ref_anaes_type as AnaestheticType,
''Central'' as Area,
''Wpas'' as Source,
wl.HEALTH_RISK_FACTOR as HealthRiskFactor,
wl.WEIGHTED_PR_F as WeightedPRF,
wl.PERCENTAGE_OVERRUN as PercentageOverRun,  
wl.ARMED_SERVICES_KEYNOTE as ArmedServicesKeyNote,
padloc.provider_code as Site,
--wl.Theatre_Type as TheatreType,  
r.thr_type as TheatreType,
r.datonsys as DateOnSystem,
wl.APPT_DIR_DESC as AppointmentDirective,
wl.Adjusted_Days as DaysAdjusted,
wl.Session_Key as ClinicSessionKey,
wl.NEXT_APPT_DATE as DateNextAppointment,
wl.LAST_EVENT_DATE as DateLastEvent,
wl.LAST_EVENT_CODE as LastEvent,
wl.LAST_EVENT_CONS as HCPLastEvent,
wl.LAST_EVENT_SPEC as SpecialtyLastEvent,
--wl.LAST_ACT_OUTCOME as LastActOutcome,
O3.OUTCOME_CODE as LastActivityOutcome,
--wl.LAST_ACT_TYPE as LastActType,
CASE WHEN TT.TRt_type is null  then OU.OUTCOME_CODE ELSE TT.TRt_type END as LastActivityType,
wl.LAST_EVENT_LOC as LastEventLoc,
wl.FU_ACTNOTEKEY as ActNotekeyFU,
wl.FU_TO_COME_IN_DATE as DateFUToComeIn,
wl.PLANNED_ASA_GRADE as PlannedASAGrade,
--wl.INTENDED_ADMIT_METHOD as IntendedAdmitMethod,
m2.method as AdmissionMethodIntended,
--wl.wLIST AS WaitingListType,
''DC'' as WaitingListType, 
wl.DOC_REFERENCE_NO AS DocumentReference,
wl.VIRTUAL_TYPE as VirtualType,
wl.CONSULT_METHOD as ConsultMethod,
wl.PREVIOUS_VIRTUAL_TYPE as PreviousVirtualType,
wl.PREVIOUS_CONSULT_METHOD as PreviousConsultMethod,
wl.PREF_VIRTUAL_TYPE as PreferredVirtualType,
wl.PREF_CONSULT_METHOD as PreferredConsultMethod,
wl.VIRTUAL_CONTACT_DETAILS as VirtualContactDetail,
wl.ELECTIVE_PRIORITY_LEVEL as ElectivePriorityLevel,
wl.REPRIORITISED_TAGET_DATE as DateReprioritisedTarget,
wl.ADMIT_METHOD AS AdmissionMethodRePrioritised,
cast(pathway_notes as varchar (3000)) as PathwayNote,
Null as DaysSuspension,
Null as DaysDNASuspension,
Null as DateDNA,
Null as DateLastPreOp,
Null as LastPreOpAttendanceStatus,
Null as DateConsultantChangeRefused,
Null as ListReviewStatus,
Null as TotalAdmissionOffers,
Null as DateAppointmentRescheduled,
Null as IntendedManagement,
Null as DateReferralRequestReceived,
Null as DateReferralSent,
Null as ReferralReason,
Null as LocalReferralUrgnc,
Null as LocalReferralPrity,
Null as DateLastSuspensionStart,
Null as DateLastSuspensionEnd,
Null as LastSuspensionReason,
Null as DateLastWaitingListReview,
Null as LastWaitingListReviewStatus,
Null as LastWaitingListReviewBatchNumber,
Null as EisQueryId,
Null as ElectiveAdmissionType,
Null as LocalWLType,
rep.priority_by as HCPRePrioritisedBy,
rep.priority_date as DateRePrioritised,
Null as PriorityClinical,
wl.DISCHARGE_DATE as DateDischargeOfLastAdmission,
wl.NEXT_APPT_NEEDED as NextApptNeeded,
null as DateDDTA



/*
r.CLIN_REF_DATE as ClinicalReferralDate,
TT.TRT_TYPE as TRT_TYPE2, 
ou.OUTCOME_CODE AS outcome_code2,
*/

	from 
	
		REF_WAIT_LEN_VIEW_ENH (''31'',''' + @TodayDateText + ''','''','''','''','''') as wl
		left join Refer R on WL.LinkID = R.LINKID
		left join coding c on c.linkid = wl.linkid and((c.itemno=1) or (c.itemno is null)) and c.when_coded = ''4'' and code_type =''OP''
		left join padloc on wl.loc = padloc.loccode
		left join GP2 on r.cons = gp2.practice
		left join TRT_TYPE TT ON TT.trt_DESCRIPTION = wl.LAST_act_type 
        left join OUTCOME OU ON OU.DESCRIPT = wl.LAST_act_type
		left join OUTCOME O3 ON O3.DESCRIPT = wl.LAST_act_OUTCOME
		left join ADMITMTH m2 on m2.description = wl.INTENDED_ADMIT_METHOD
		left join PATHWAYMGT pm ON pm.UPI = wl.RTT_UPI and (coalesce (pm.event_Source, ''PN'') = ''PN'' and pm.pwaykey = (select first 1 pm2.pwaykey from pathwaymgt pm2 where pm2.UPI = wl.RTT_UPI and coalesce(pm2.event_source, ''PN'') = ''PN''))
		left join REF_ELECTIVE_REPRIORITISED rep on rep.seqno = (select first 1 seqno from REF_ELECTIVE_REPRIORITISED r2 where r2.linkid = wl.linkid order by date_entered desc) 

union

Select distinct

wl.LOS AS DaysWait,
wl.NHS AS NHSNumber,
wl.CaseNo as LocalPatientIdentifier,
wl.dat_ref as DateReferred,
wl.LinkID as SystemLinkID,
wl.INTENT_REFER AS ReferralIntent,
wl.GP_REF as Referrer,
wl.GP_PRAC AS ReferringOrganisation,
wl.Reg_GP as GPAtTimeOfActivity,
wl.Reg_Prac as GPPracticeAtTimeOfActivity,
wl.Postcode as PostcodeAtTimeOfActivity,
wl.DHA_CODE as Commissioner,
wl.Source_Refer as ReferralSource,
wl.LTTR_PRTY AS PriorityOnLetter,
wl.Ref_Outcome as Outcome,
wl.Datonsys as DateOnWaitingList,
wl.Loc as Location,
wl.Category as PatientCategory,
wl.Cons_Prty as PriorityOfHCP,
wl.trt_type as TreatmentType,
wl.Date_Booked as DateBooked,
wl.Reason_Booked as ReasonBooked,
wl.GPREFNO as GpRefNo,
wl.Clinical_Condition as ClinicalCondition,
wl.Charged_To as CommissionerType,
wl.TRT_DATE as DateOfAppointment, 
wl.Deferred_Date as DateDeferred,
wl.Spec as Specialty,
wl.List_Outcome as ListStatus,    
wl.Contracts_Authorised as ContractsAuthorised,  
wl.origtext as Comments,
wl.AgeInDays as AgeInDays,
wl.Suspended as Suspended, 
wl.Orig_Diag_description as OriginalDiagnosis,
wl.Exclude_PPO1W as ExcludeFromWLReporting,
wl.ACTNOTEKEY as ActNoteKey,
wl.RTT_UPI as UniquePathwayIdentifier,
wl.RTT_Start_Date as DateRTTStart,
wl.RTT_Stop_Date as DateRTTStop,
wl.RTT_LOW AS RTTWait,
wl.RTT_Adjusted_LOW as RTTWaitAdjusted,
wl.RTT_Spec AS RTTSpecialty,
wl.RTT_ACTNOTEKEY_Start as RTTActNotekeyAtStart,
wl.RTT_Exclude AS RTTExcludedSpecialty,
wl.Planned_OP_Date as DatePlanned,
wl.RTT_Start_Source as RTTSourceAtStart,
wl.RTT_Start_Type as RTTTypeAtStart,
wl.RTT_Target_Date as DateRTTTarget,
wl.RTT_TARGET AS RTTTargetDays,
wl.Pathway_Stage  as RTTStage,
NULL as DateOfLastDNAOrPatientCancelled,
NULL as CommentsFromWaitingList,
NULL as WaitingListRefNo,
NULL as ScheduleRefNo,
NULL as ReferralRefNo,
c.THECODE as OPCS,
NULL as ProcedureProposed,
GP2.GP_CODE as HCP,
wl.TARGET_DATE as DateOfOriginalTarget,
cast(''Now'' as Date) as DateWaitingListCensus,
r.pref_ward as BookedWardOrClinic,
NULL as CommentsOfReferral,
NULL as TimeEstimatedInTheatre,
--wl.Anaesthetic_Type as AnaestheticType,
r.ref_anaes_type as AnaestheticType,
''Central'' as Area,
''Wpas'' as Source,
wl.HEALTH_RISK_FACTOR as HealthRiskFactor,
wl.WEIGHTED_PR_F as WeightedPRF,
wl.PERCENTAGE_OVERRUN as PercentageOverRun,  
wl.ARMED_SERVICES_KEYNOTE as ArmedServicesKeyNote,
padloc.provider_code as Site,
--wl.Theatre_Type as TheatreType,  
r.thr_type as TheatreType,
r.datonsys as DateOnSystem,
wl.APPT_DIR_DESC as AppointmentDirective,
wl.Adjusted_Days as DaysAdjusted,
wl.Session_Key as ClinicSessionKey,
wl.NEXT_APPT_DATE as DateNextAppointment,
wl.LAST_EVENT_DATE as DateLastEvent,
wl.LAST_EVENT_CODE as LastEvent,
wl.LAST_EVENT_CONS as HCPLastEvent,
wl.LAST_EVENT_SPEC as SpecialtyLastEvent,
--wl.LAST_ACT_OUTCOME as LastActOutcome,
O3.OUTCOME_CODE as LastActivityOutcome,
--wl.LAST_ACT_TYPE as LastActType,
CASE WHEN TT.TRt_type is null  then OU.OUTCOME_CODE ELSE TT.TRt_type END as LastActivityType,
wl.LAST_EVENT_LOC as LastEventLoc,
wl.FU_ACTNOTEKEY as ActNotekeyFU,
wl.FU_TO_COME_IN_DATE as DateFUToComeIn,
wl.PLANNED_ASA_GRADE as PlannedASAGrade,
--wl.INTENDED_ADMIT_METHOD as IntendedAdmitMethod,
m2.method as AdmissionMethodIntended,
--wl.wLIST AS WaitingListType,
''IP'' as WaitingListType, 
wl.DOC_REFERENCE_NO AS DocumentReference,
wl.VIRTUAL_TYPE as VirtualType,
wl.CONSULT_METHOD as ConsultMethod,
wl.PREVIOUS_VIRTUAL_TYPE as PreviousVirtualType,
wl.PREVIOUS_CONSULT_METHOD as PreviousConsultMethod,
wl.PREF_VIRTUAL_TYPE as PreferredVirtualType,
wl.PREF_CONSULT_METHOD as PreferredConsultMethod,
wl.VIRTUAL_CONTACT_DETAILS as VirtualContactDetail,
wl.ELECTIVE_PRIORITY_LEVEL as ElectivePriorityLevel,
wl.REPRIORITISED_TAGET_DATE as DateReprioritisedTarget,
wl.ADMIT_METHOD AS AdmissionMethodRePrioritised,
cast(pathway_notes as varchar (3000)) as PathwayNote,
Null as DaysSuspension,
Null as DaysDNASuspension,
Null as DateDNA,
Null as DateLastPreOp,
Null as LastPreOpAttendanceStatus,
Null as DateConsultantChangeRefused,
Null as ListReviewStatus,
Null as TotalAdmissionOffers,
Null as DateAppointmentRescheduled,
Null as IntendedManagement,
Null as DateReferralRequestReceived,
Null as DateReferralSent,
Null as ReferralReason,
Null as LocalReferralUrgnc,
Null as LocalReferralPrity,
Null as DateLastSuspensionStart,
Null as DateLastSuspensionEnd,
Null as LastSuspensionReason,
Null as DateLastWaitingListReview,
Null as LastWaitingListReviewStatus,
Null as LastWaitingListReviewBatchNumber,
Null as EisQueryId,
Null as ElectiveAdmissionType,
Null as LocalWLType,
rep.priority_by as HCPRePrioritisedBy,
rep.priority_date as DateRePrioritised,
Null as PriorityClinical,
wl.DISCHARGE_DATE as DateDischargeOfLastAdmission,
wl.NEXT_APPT_NEEDED as NextApptNeeded,
null as DateDDTA


/*
r.CLIN_REF_DATE as ClinicalReferralDate,
TT.TRT_TYPE as TRT_TYPE2, 
ou.OUTCOME_CODE AS outcome_code2,
*/

	from 
	
		REF_WAIT_LEN_VIEW_ENH (''41'',''' + @TodayDateText + ''','''','''','''','''') as wl
		left join Refer R on WL.LinkID = R.LINKID
		left join coding c on c.linkid = wl.linkid and((c.itemno=1) or (c.itemno is null)) and c.when_coded = ''4'' and code_type =''OP''
		left join padloc on wl.loc = padloc.loccode
		left join GP2 on r.cons = gp2.practice
		left join TRT_TYPE TT ON TT.trt_DESCRIPTION = wl.LAST_act_type 
        left join OUTCOME OU ON OU.DESCRIPT = wl.LAST_act_type
		left join OUTCOME O3 ON O3.DESCRIPT = wl.LAST_act_OUTCOME
		left join ADMITMTH m2 on m2.description = wl.INTENDED_ADMIT_METHOD
		left join PATHWAYMGT pm ON pm.UPI = wl.RTT_UPI and (coalesce (pm.event_Source, ''PN'') = ''PN'' and pm.pwaykey = (select first 1 pm2.pwaykey from pathwaymgt pm2 where pm2.UPI = wl.RTT_UPI and coalesce(pm2.event_source, ''PN'') = ''PN''))
		left join REF_ELECTIVE_REPRIORITISED rep on rep.seqno = (select first 1 seqno from REF_ELECTIVE_REPRIORITISED r2 where r2.linkid = wl.linkid order by date_entered desc) 

union

Select distinct

wl.LOS AS DaysWait,
wl.NHS AS NHSNumber,
wl.CaseNo as LocalPatientIdentifier,
wl.dat_ref as DateReferred,
wl.LinkID as SystemLinkID,
wl.INTENT_REFER AS ReferralIntent,
wl.GP_REF as Referrer,
wl.GP_PRAC AS ReferringOrganisation,
wl.Reg_GP as GPAtTimeOfActivity,
wl.Reg_Prac as GPPracticeAtTimeOfActivity,
wl.Postcode as PostcodeAtTimeOfActivity,
wl.DHA_CODE as Commissioner,
wl.Source_Refer as ReferralSource,
wl.LTTR_PRTY AS PriorityOnLetter,
wl.Ref_Outcome as Outcome,
wl.Datonsys as DateOnWaitingList,
wl.Loc as Location,
wl.Category as PatientCategory,
wl.Cons_Prty as PriorityOfHCP,
wl.trt_type as TreatmentType,
wl.Date_Booked as DateBooked,
wl.Reason_Booked as ReasonBooked,
wl.GPREFNO as GpRefNo,
wl.Clinical_Condition as ClinicalCondition,
wl.Charged_To as CommissionerType,
wl.TRT_DATE as DateOfAppointment, 
wl.Deferred_Date as DateDeferred,
wl.Spec as Specialty,
wl.List_Outcome as ListStatus,    
wl.Contracts_Authorised as ContractsAuthorised,  
wl.origtext as Comments,
wl.AgeInDays as AgeInDays,
wl.Suspended as Suspended, 
wl.Orig_Diag_description as OriginalDiagnosis,
wl.Exclude_PPO1W as ExcludeFromWLReporting,
wl.ACTNOTEKEY as ActNoteKey,
wl.RTT_UPI as UniquePathwayIdentifier,
wl.RTT_Start_Date as DateRTTStart,
wl.RTT_Stop_Date as DateRTTStop,
wl.RTT_LOW AS RTTWait,
wl.RTT_Adjusted_LOW as RTTWaitAdjusted,
wl.RTT_Spec AS RTTSpecialty,
wl.RTT_ACTNOTEKEY_Start as RTTActNotekeyAtStart,
wl.RTT_Exclude AS RTTExcludedSpecialty,
wl.Planned_OP_Date as DatePlanned,
wl.RTT_Start_Source as RTTSourceAtStart,
wl.RTT_Start_Type as RTTTypeAtStart,
wl.RTT_Target_Date as DateRTTTarget,
wl.RTT_TARGET AS RTTTargetDays,
wl.Pathway_Stage  as RTTStage,
NULL as DateOfLastDNAOrPatientCancelled,
NULL as CommentsFromWaitingList,
NULL as WaitingListRefNo,
NULL as ScheduleRefNo,
NULL as ReferralRefNo,
c.THECODE as OPCS,
NULL as ProcedureProposed,
GP2.GP_CODE as HCP,
wl.TARGET_DATE as DateOfOriginalTarget,
cast(''Now'' as Date) as DateWaitingListCensus,
r.pref_ward as BookedWardOrClinic,
NULL as CommentsOfReferral,
NULL as TimeEstimatedInTheatre,
--wl.Anaesthetic_Type as AnaestheticType,
r.ref_anaes_type as AnaestheticType,
''Central'' as Area,
''Wpas'' as Source,
wl.HEALTH_RISK_FACTOR as HealthRiskFactor,
wl.WEIGHTED_PR_F as WeightedPRF,
wl.PERCENTAGE_OVERRUN as PercentageOverRun,  
wl.ARMED_SERVICES_KEYNOTE as ArmedServicesKeyNote,
padloc.provider_code as Site,
--wl.Theatre_Type as TheatreType,  
r.thr_type as TheatreType,
r.datonsys as DateOnSystem,
wl.APPT_DIR_DESC as AppointmentDirective,
wl.Adjusted_Days as DaysAdjusted,
wl.Session_Key as ClinicSessionKey,
wl.NEXT_APPT_DATE as DateNextAppointment,
wl.LAST_EVENT_DATE as DateLastEvent,
wl.LAST_EVENT_CODE as LastEvent,
wl.LAST_EVENT_CONS as HCPLastEvent,
wl.LAST_EVENT_SPEC as SpecialtyLastEvent,
--wl.LAST_ACT_OUTCOME as LastActivityOutcome,
O3.OUTCOME_CODE as LastActivityOutcome,
--wl.LAST_ACT_TYPE as LastActType,
CASE WHEN TT.TRt_type is null  then OU.OUTCOME_CODE ELSE TT.TRt_type END as LastActivityType,
wl.LAST_EVENT_LOC as LastEventLoc,
wl.FU_ACTNOTEKEY as ActNotekeyFU,
wl.FU_TO_COME_IN_DATE as DateFUToComeIn,
wl.PLANNED_ASA_GRADE as PlannedASAGrade,
--wl.INTENDED_ADMIT_METHOD as IntendedAdmitMethod,
m2.method as AdmissionMethodIntended,
--wl.wLIST AS WaitingListType,
''FU'' as WaitingListType, 
wl.DOC_REFERENCE_NO AS DocumentReference,
wl.VIRTUAL_TYPE as VirtualType,
wl.CONSULT_METHOD as ConsultMethod,
wl.PREVIOUS_VIRTUAL_TYPE as PreviousVirtualType,
wl.PREVIOUS_CONSULT_METHOD as PreviousConsultMethod,
wl.PREF_VIRTUAL_TYPE as PreferredVirtualType,
wl.PREF_CONSULT_METHOD as PreferredConsultMethod,
wl.VIRTUAL_CONTACT_DETAILS as VirtualContactDetail,
wl.ELECTIVE_PRIORITY_LEVEL as ElectivePriorityLevel,
wl.REPRIORITISED_TAGET_DATE as DateReprioritisedTarget,
wl.ADMIT_METHOD AS AdmissionMethodRePrioritised,
cast(pathway_notes as varchar (3000)) as PathwayNote,
Null as DaysSuspension,
Null as DaysDNASuspension,
Null as DateDNA,
Null as DateLastPreOp,
Null as LastPreOpAttendanceStatus,
Null as DateConsultantChangeRefused,
Null as ListReviewStatus,
Null as TotalAdmissionOffers,
Null as DateAppointmentRescheduled,
Null as IntendedManagement,
Null as DateReferralRequestReceived,
Null as DateReferralSent,
Null as ReferralReason,
Null as LocalReferralUrgnc,
Null as LocalReferralPrity,
Null as DateLastSuspensionStart,
Null as DateLastSuspensionEnd,
Null as LastSuspensionReason,
Null as DateLastWaitingListReview,
Null as LastWaitingListReviewStatus,
Null as LastWaitingListReviewBatchNumber,
Null as EisQueryId,
Null as ElectiveAdmissionType,
Null as LocalWLType,
rep.priority_by as HCPRePrioritisedBy,
rep.priority_date as DateRePrioritised,
Null as PriorityClinical,
wl.DISCHARGE_DATE as DateDischargeOfLastAdmission,
wl.NEXT_APPT_NEEDED as NextApptNeeded,
null as DateDDTA



/*
r.CLIN_REF_DATE as ClinicalReferralDate,
TT.TRT_TYPE as TRT_TYPE2, 
ou.OUTCOME_CODE AS outcome_code2,
*/

	from 
	
		REF_WAIT_LEN_VIEW_ENH (''FU'',''01/01/2999'','''','''','''','''') as wl
		left join Refer R on WL.LinkID = R.LINKID
		left join coding c on c.linkid = wl.linkid and((c.itemno=1) or (c.itemno is null)) and c.when_coded = ''4'' and code_type =''OP''
		left join padloc on wl.loc = padloc.loccode
		left join GP2 on r.cons = gp2.practice
		left join TRT_TYPE TT ON TT.trt_DESCRIPTION = wl.LAST_act_type 
        left join OUTCOME OU ON OU.DESCRIPT = wl.LAST_act_type
		left join OUTCOME O3 ON O3.DESCRIPT = wl.LAST_act_OUTCOME
		left join ADMITMTH m2 on m2.description = wl.INTENDED_ADMIT_METHOD
		left join PATHWAYMGT pm ON pm.UPI = wl.RTT_UPI and (coalesce (pm.event_Source, ''PN'') = ''PN'' and pm.pwaykey = (select first 1 pm2.pwaykey from pathwaymgt pm2 where pm2.UPI = wl.RTT_UPI and coalesce(pm2.event_source, ''PN'') = ''PN''))
		left join REF_ELECTIVE_REPRIORITISED rep on rep.seqno = (select first 1 seqno from REF_ELECTIVE_REPRIORITISED r2 where r2.linkid = wl.linkid order by date_entered desc) 


union

Select distinct

wl.LOS AS DaysWait,
wl.NHS AS NHSNumber,
wl.CaseNo as LocalPatientIdentifier,
wl.dat_ref as DateReferred,
wl.LinkID as SystemLinkID,
wl.INTENT_REFER AS ReferralIntent,
wl.GP_REF as Referrer,
wl.GP_PRAC AS ReferringOrganisation,
wl.Reg_GP as GPAtTimeOfActivity,
wl.Reg_Prac as GPPracticeAtTimeOfActivity,
wl.Postcode as PostcodeAtTimeOfActivity,
wl.DHA_CODE as Commissioner,
wl.Source_Refer as ReferralSource,
wl.LTTR_PRTY AS PriorityOnLetter,
wl.Ref_Outcome as Outcome,
wl.Datonsys as DateOnWaitingList,
wl.Loc as Location,
wl.Category as PatientCategory,
wl.Cons_Prty as PriorityOfHCP,
wl.trt_type as TreatmentType,
wl.Date_Booked as DateBooked,
wl.Reason_Booked as ReasonBooked,
wl.GPREFNO as GpRefNo,
wl.Clinical_Condition as ClinicalCondition,
wl.Charged_To as CommissionerType,
wl.TRT_DATE as DateOfAppointment, 
wl.Deferred_Date as DateDeferred,
wl.Spec as Specialty,
wl.List_Outcome as ListStatus,    
wl.Contracts_Authorised as ContractsAuthorised,  
wl.origtext as Comments,
wl.AgeInDays as AgeInDays,
wl.Suspended as Suspended, 
wl.Orig_Diag_description as OriginalDiagnosis,
wl.Exclude_PPO1W as ExcludeFromWLReporting,
wl.ACTNOTEKEY as ActNoteKey,
wl.RTT_UPI as UniquePathwayIdentifier,
wl.RTT_Start_Date as DateRTTStart,
wl.RTT_Stop_Date as DateRTTStop,
wl.RTT_LOW AS RTTWait,
wl.RTT_Adjusted_LOW as RTTWaitAdjusted,
wl.RTT_Spec AS RTTSpecialty,
wl.RTT_ACTNOTEKEY_Start as RTTActNotekeyAtStart,
wl.RTT_Exclude AS RTTExcludedSpecialty,
wl.Planned_OP_Date as DatePlanned,
wl.RTT_Start_Source as RTTSourceAtStart,
wl.RTT_Start_Type as RTTTypeAtStart,
wl.RTT_Target_Date as DateRTTTarget,
wl.RTT_TARGET AS RTTTargetDays,
wl.Pathway_Stage  as RTTStage,
NULL as DateOfLastDNAOrPatientCancelled,
NULL as CommentsFromWaitingList,
NULL as WaitingListRefNo,
NULL as ScheduleRefNo,
NULL as ReferralRefNo,
c.THECODE as OPCS,
NULL as ProcedureProposed,
GP2.GP_CODE as HCP,
wl.TARGET_DATE as DateOfOriginalTarget,
cast(''Now'' as Date) as DateWaitingListCensus,
r.pref_ward as BookedWardOrClinic,
NULL as CommentsOfReferral,
NULL as TimeEstimatedInTheatre,
--wl.Anaesthetic_Type as AnaestheticType,
r.ref_anaes_type as AnaestheticType,
''Central'' as Area,
''Wpas'' as Source,
wl.HEALTH_RISK_FACTOR as HealthRiskFactor,
wl.WEIGHTED_PR_F as WeightedPRF,
wl.PERCENTAGE_OVERRUN as PercentageOverRun,  
wl.ARMED_SERVICES_KEYNOTE as ArmedServicesKeyNote,
padloc.provider_code as Site,
--wl.Theatre_Type as TheatreType,  
r.thr_type as TheatreType,
r.datonsys as DateOnSystem,
wl.APPT_DIR_DESC as AppointmentDirective,
wl.Adjusted_Days as DaysAdjusted,
wl.Session_Key as ClinicSessionKey,
wl.NEXT_APPT_DATE as DateNextAppointment,
wl.LAST_EVENT_DATE as DateLastEvent,
wl.LAST_EVENT_CODE as LastEvent,
wl.LAST_EVENT_CONS as HCPLastEvent,
wl.LAST_EVENT_SPEC as SpecialtyLastEvent,
--wl.LAST_ACT_OUTCOME as LastActOutcome,
O3.OUTCOME_CODE as LastActtivityOutcome,
--wl.LAST_ACT_TYPE as LastActType,
CASE WHEN TT.TRt_type is null  then OU.OUTCOME_CODE ELSE TT.TRt_type END as LastActivityType,
wl.LAST_EVENT_LOC as LastEventLoc,
wl.FU_ACTNOTEKEY as ActNotekeyFU,
wl.FU_TO_COME_IN_DATE as DateFUToComeIn,
wl.PLANNED_ASA_GRADE as PlannedASAGrade,
--wl.INTENDED_ADMIT_METHOD as IntendedAdmitMethod,
m2.method as AdmissionMethodIntended,
--wl.wLIST AS WaitingListType,
''PP'' as WaitingListType, 
wl.DOC_REFERENCE_NO AS DocumentReference,
wl.VIRTUAL_TYPE as VirtualType,
wl.CONSULT_METHOD as ConsultMethod,
wl.PREVIOUS_VIRTUAL_TYPE as PreviousVirtualType,
wl.PREVIOUS_CONSULT_METHOD as PreviousConsultMethod,
wl.PREF_VIRTUAL_TYPE as PreferredVirtualType,
wl.PREF_CONSULT_METHOD as PreferredConsultMethod,
wl.VIRTUAL_CONTACT_DETAILS as VirtualContactDetail,
wl.ELECTIVE_PRIORITY_LEVEL as ElectivePriorityLevel,
wl.REPRIORITISED_TAGET_DATE as DateReprioritisedTarget,
wl.ADMIT_METHOD AS AdmissionMethodRePrioritised,
cast(pathway_notes as varchar (3000)) as PathwayNote,
Null as DaysSuspension,
Null as DaysDNASuspension,
Null as DateDNA,
Null as DateLastPreOp,
Null as LastPreOpAttendanceStatus,
Null as DateConsultantChangeRefused,
Null as ListReviewStatus,
Null as TotalAdmissionOffers,
Null as DateAppointmentRescheduled,
Null as IntendedManagement,
Null as DateReferralRequestReceived,
Null as DateReferralSent,
Null as ReferralReason,
Null as LocalReferralUrgnc,
Null as LocalReferralPrity,
Null as DateLastSuspensionStart,
Null as DateLastSuspensionEnd,
Null as LastSuspensionReason,
Null as DateLastWaitingListReview,
Null as LastWaitingListReviewStatus,
Null as LastWaitingListReviewBatchNumber,
Null as EisQueryId,
Null as ElectiveAdmissionType,
Null as LocalWLType,
rep.priority_by as HCPRePrioritisedBy,
rep.priority_date as DateRePrioritised,
Null as PriorityClinical,
wl.DISCHARGE_DATE as DateDischargeOfLastAdmission,
wl.NEXT_APPT_NEEDED as NextApptNeeded,
null as DateDDTA


/*
r.CLIN_REF_DATE as ClinicalReferralDate,
TT.TRT_TYPE as TRT_TYPE2, 
ou.OUTCOME_CODE AS outcome_code2,
*/

	from 
	
		REF_WAIT_LEN_VIEW_ENH (''PP'',''' + @TodayDateText + ''','''','''','''','''') as wl
		left join Refer R on WL.LinkID = R.LINKID
		left join coding c on c.linkid = wl.linkid and((c.itemno=1) or (c.itemno is null)) and c.when_coded = ''4'' and code_type =''OP''
		left join padloc on wl.loc = padloc.loccode
		left join GP2 on r.cons = gp2.practice
		left join TRT_TYPE TT ON TT.trt_DESCRIPTION = wl.LAST_act_type 
        left join OUTCOME OU ON OU.DESCRIPT = wl.LAST_act_type
		left join OUTCOME O3 ON O3.DESCRIPT = wl.LAST_act_OUTCOME
		left join ADMITMTH m2 on m2.description = wl.INTENDED_ADMIT_METHOD
		left join PATHWAYMGT pm ON pm.UPI = wl.RTT_UPI and (coalesce (pm.event_Source, ''PN'') = ''PN'' and pm.pwaykey = (select first 1 pm2.pwaykey from pathwaymgt pm2 where pm2.UPI = wl.RTT_UPI and coalesce(pm2.event_source, ''PN'') = ''PN''))
		left join REF_ELECTIVE_REPRIORITISED rep on rep.seqno = (select first 1 seqno from REF_ELECTIVE_REPRIORITISED r2 where r2.linkid = wl.linkid order by date_entered desc) 

union

Select distinct

wl.LOS AS DaysWait,
wl.NHS AS NHSNumber,
wl.CaseNo as LocalPatientIdentifier,
wl.dat_ref as DateReferred,
wl.LinkID as SystemLinkID,
wl.INTENT_REFER AS ReferralIntent,
wl.GP_REF as Referrer,
wl.GP_PRAC AS ReferringOrganisation,
wl.Reg_GP as GPAtTimeOfActivity,
wl.Reg_Prac as GPPracticeAtTimeOfActivity,
wl.Postcode as PostcodeAtTimeOfActivity,
wl.DHA_CODE as Commissioner,
wl.Source_Refer as ReferralSource,
wl.LTTR_PRTY AS PriorityOnLetter,
wl.Ref_Outcome as Outcome,
wl.Datonsys as DateOnWaitingList,
wl.Loc as Location,
wl.Category as PatientCategory,
wl.Cons_Prty as PriorityOfHCP,
wl.trt_type as TreatmentType,
wl.Date_Booked as DateBooked,
wl.Reason_Booked as ReasonBooked,
wl.GPREFNO as GpRefNo,
wl.Clinical_Condition as ClinicalCondition,
wl.Charged_To as CommissionerType,
wl.TRT_DATE as DateOfAppointment, 
wl.Deferred_Date as DateDeferred,
wl.Spec as Specialty,
wl.List_Outcome as ListStatus,    
wl.Contracts_Authorised as ContractsAuthorised,  
wl.origtext as Comments,
wl.AgeInDays as AgeInDays,
wl.Suspended as Suspended, 
wl.Orig_Diag_description as OriginalDiagnosis,
wl.Exclude_PPO1W as ExcludeFromWLReporting,
wl.ACTNOTEKEY as ActNoteKey,
wl.RTT_UPI as UniquePathwayIdentifier,
wl.RTT_Start_Date as DateRTTStart,
wl.RTT_Stop_Date as DateRTTStop,
wl.RTT_LOW AS RTTWait,
wl.RTT_Adjusted_LOW as RTTWaitAdjusted,
wl.RTT_Spec AS RTTSpecialty,
wl.RTT_ACTNOTEKEY_Start as RTTActNotekeyAtStart,
wl.RTT_Exclude AS RTTExcludedSpecialty,
wl.Planned_OP_Date as DatePlanned,
wl.RTT_Start_Source as RTTSourceAtStart,
wl.RTT_Start_Type as RTTTypeAtStart,
wl.RTT_Target_Date as DateRTTTarget,
wl.RTT_TARGET AS RTTTargetDays,
wl.Pathway_Stage  as RTTStage,
NULL as DateOfLastDNAOrPatientCancelled,
NULL as CommentsFromWaitingList,
NULL as WaitingListRefNo,
NULL as ScheduleRefNo,
NULL as ReferralRefNo,
c.THECODE as OPCS,
NULL as ProcedureProposed,
GP2.GP_CODE as HCP,
wl.TARGET_DATE as DateOfOriginalTarget,
cast(''Now'' as Date) as DateWaitingListCensus,
r.pref_ward as BookedWardOrClinic,
NULL as CommentsOfReferral,
NULL as TimeEstimatedInTheatre,
--wl.Anaesthetic_Type as AnaestheticType,
r.ref_anaes_type as AnaestheticType,
''Central'' as Area,
''Wpas'' as Source,
wl.HEALTH_RISK_FACTOR as HealthRiskFactor,
wl.WEIGHTED_PR_F as WeightedPRF,
wl.PERCENTAGE_OVERRUN as PercentageOverRun,  
wl.ARMED_SERVICES_KEYNOTE as ArmedServicesKeyNote,
padloc.provider_code as Site,
--wl.Theatre_Type as TheatreType,  
r.thr_type as TheatreType,
r.datonsys as DateOnSystem,
wl.APPT_DIR_DESC as AppointmentDirective,
wl.Adjusted_Days as DaysAdjusted,
wl.Session_Key as ClinicSessionKey,
wl.NEXT_APPT_DATE as DateNextAppointment,
wl.LAST_EVENT_DATE as DateLastEvent,
wl.LAST_EVENT_CODE as LastEvent,
wl.LAST_EVENT_CONS as HCPLastEvent,
wl.LAST_EVENT_SPEC as SpecialtyLastEvent,
--wl.LAST_ACT_OUTCOME as LastActOutcome,
O3.OUTCOME_CODE as LastActivityOutcome,
--wl.LAST_ACT_TYPE as LastActType,
CASE WHEN TT.TRt_type is null  then OU.OUTCOME_CODE ELSE TT.TRt_type END as LastActivityType,
wl.LAST_EVENT_LOC as LastEventLoc,
wl.FU_ACTNOTEKEY as ActNotekeyFU,
wl.FU_TO_COME_IN_DATE as DateFUToComeIn,
wl.PLANNED_ASA_GRADE as PlannedASAGrade,
--wl.INTENDED_ADMIT_METHOD as IntendedAdmitMethod,
m2.method as AdmissionMethodIntended,
--wl.wLIST AS WaitingListType,
''EF'' as WaitingListType, 
wl.DOC_REFERENCE_NO AS DocumentReference,
wl.VIRTUAL_TYPE as VirtualType,
wl.CONSULT_METHOD as ConsultMethod,
wl.PREVIOUS_VIRTUAL_TYPE as PreviousVirtualType,
wl.PREVIOUS_CONSULT_METHOD as PreviousConsultMethod,
wl.PREF_VIRTUAL_TYPE as PreferredVirtualType,
wl.PREF_CONSULT_METHOD as PreferredConsultMethod,
wl.VIRTUAL_CONTACT_DETAILS as VirtualContactDetail,
wl.ELECTIVE_PRIORITY_LEVEL as ElectivePriorityLevel,
wl.REPRIORITISED_TAGET_DATE as DateReprioritisedTarget,
wl.ADMIT_METHOD AS AdmissionMethodRePrioritised,
cast(pathway_notes as varchar (3000)) as PathwayNote,
Null as DaysSuspension,
Null as DaysDNASuspension,
Null as DateDNA,
Null as DateLastPreOp,
Null as LastPreOpAttendanceStatus,
Null as DateConsultantChangeRefused,
Null as ListReviewStatus,
Null as TotalAdmissionOffers,
Null as DateAppointmentRescheduled,
Null as IntendedManagement,
Null as DateReferralRequestReceived,
Null as DateReferralSent,
Null as ReferralReason,
Null as LocalReferralUrgnc,
Null as LocalReferralPrity,
Null as DateLastSuspensionStart,
Null as DateLastSuspensionEnd,
Null as LastSuspensionReason,
Null as DateLastWaitingListReview,
Null as LastWaitingListReviewStatus,
Null as LastWaitingListReviewBatchNumber,
Null as EisQueryId,
Null as ElectiveAdmissionType,
Null as LocalWLType,
rep.priority_by as HCPRePrioritisedBy,
rep.priority_date as DateRePrioritised,
Null as PriorityClinical,
wl.DISCHARGE_DATE as DateDischargeOfLastAdmission,
wl.NEXT_APPT_NEEDED as NextApptNeeded,
null as DateDDTA


/*
r.CLIN_REF_DATE as ClinicalReferralDate,
TT.TRT_TYPE as TRT_TYPE2, 
ou.OUTCOME_CODE AS outcome_code2,
*/

	from 
	
		REF_WAIT_LEN_VIEW_ENH (''TF'',''01/01/2999'','''','''','''','''') as wl
		left join Refer R on WL.LinkID = R.LINKID
		left join coding c on c.linkid = wl.linkid and((c.itemno=1) or (c.itemno is null)) and c.when_coded = ''4'' and code_type =''OP''
		left join padloc on wl.loc = padloc.loccode
		left join GP2 on r.cons = gp2.practice
		left join TRT_TYPE TT ON TT.trt_DESCRIPTION = wl.LAST_act_type 
        left join OUTCOME OU ON OU.DESCRIPT = wl.LAST_act_type
		left join OUTCOME O3 ON O3.DESCRIPT = wl.LAST_act_OUTCOME
		left join ADMITMTH m2 on m2.description = wl.INTENDED_ADMIT_METHOD
		left join PATHWAYMGT pm ON pm.UPI = wl.RTT_UPI and (coalesce (pm.event_Source, ''PN'') = ''PN'' and pm.pwaykey = (select first 1 pm2.pwaykey from pathwaymgt pm2 where pm2.UPI = wl.RTT_UPI and coalesce(pm2.event_source, ''PN'') = ''PN''))
		left join REF_ELECTIVE_REPRIORITISED rep on rep.seqno = (select first 1 seqno from REF_ELECTIVE_REPRIORITISED r2 where r2.linkid = wl.linkid order by date_entered desc) 

UNION


Select distinct

wl.LOS AS DaysWait,
wl.NHS AS NHSNumber,
wl.CaseNo as LocalPatientIdentifier,
wl.dat_ref as DateReferred,
wl.LinkID as SystemLinkID,
wl.INTENT_REFER AS ReferralIntent,
wl.GP_REF as Referrer,
wl.GP_PRAC AS ReferringOrganisation,
wl.Reg_GP as GPAtTimeOfActivity,
wl.Reg_Prac as GPPracticeAtTimeOfActivity,
wl.Postcode as PostcodeAtTimeOfActivity,
wl.DHA_CODE as Commissioner,
wl.Source_Refer as ReferralSource,
wl.LTTR_PRTY AS PriorityOnLetter,
wl.Ref_Outcome as Outcome,
wl.Datonsys as DateOnWaitingList,
wl.Loc as Location,
wl.Category as PatientCategory,
wl.Cons_Prty as PriorityOfHCP,
wl.trt_type as TreatmentType,
wl.Date_Booked as DateBooked,
wl.Reason_Booked as ReasonBooked,
wl.GPREFNO as GpRefNo,
wl.Clinical_Condition as ClinicalCondition,
wl.Charged_To as CommissionerType,
wl.TRT_DATE as DateOfAppointment, 
wl.Deferred_Date as DateDeferred,
wl.Spec as Specialty,
wl.List_Outcome as ListStatus,    
wl.Contracts_Authorised as ContractsAuthorised,  
wl.origtext as Comments,
wl.AgeInDays as AgeInDays,
wl.Suspended as Suspended, 
wl.Orig_Diag_description as OriginalDiagnosis,
wl.Exclude_PPO1W as ExcludeFromWLReporting,
wl.ACTNOTEKEY as ActNoteKey,
wl.RTT_UPI as UniquePathwayIdentifier,
wl.RTT_Start_Date as DateRTTStart,
wl.RTT_Stop_Date as DateRTTStop,
wl.RTT_LOW AS RTTWait,
wl.RTT_Adjusted_LOW as RTTWaitAdjusted,
wl.RTT_Spec AS RTTSpecialty,
wl.RTT_ACTNOTEKEY_Start as RTTActNotekeyAtStart,
wl.RTT_Exclude AS RTTExcludedSpecialty,
wl.Planned_OP_Date as DatePlanned,
wl.RTT_Start_Source as RTTSourceAtStart,
wl.RTT_Start_Type as RTTTypeAtStart,
wl.RTT_Target_Date as DateRTTTarget,
wl.RTT_TARGET AS RTTTargetDays,
wl.Pathway_Stage  as RTTStage,
NULL as DateOfLastDNAOrPatientCancelled,
NULL as CommentsFromWaitingList,
NULL as WaitingListRefNo,
NULL as ScheduleRefNo,
NULL as ReferralRefNo,
c.THECODE as OPCS,
NULL as ProcedureProposed,
GP2.GP_CODE as HCP,
wl.TARGET_DATE as DateOfOriginalTarget,
cast(''Now'' as Date) as DateWaitingListCensus,
r.pref_ward as BookedWardOrClinic,
NULL as CommentsOfReferral,
NULL as TimeEstimatedInTheatre,
--wl.Anaesthetic_Type as AnaestheticType,
r.ref_anaes_type as AnaestheticType,
''Central'' as Area,
''Wpas'' as Source,
wl.HEALTH_RISK_FACTOR as HealthRiskFactor,
wl.WEIGHTED_PR_F as WeightedPRF,
wl.PERCENTAGE_OVERRUN as PercentageOverRun,  
wl.ARMED_SERVICES_KEYNOTE as ArmedServicesKeyNote,
padloc.provider_code as Site,
--wl.Theatre_Type as TheatreType,  
r.thr_type as TheatreType,
r.datonsys as DateOnSystem,
wl.APPT_DIR_DESC as AppointmentDirective,
wl.Adjusted_Days as DaysAdjusted,
wl.Session_Key as ClinicSessionKey,
wl.NEXT_APPT_DATE as DateNextAppointment,
wl.LAST_EVENT_DATE as DateLastEvent,
wl.LAST_EVENT_CODE as LastEvent,
wl.LAST_EVENT_CONS as HCPLastEvent,
wl.LAST_EVENT_SPEC as SpecialtyLastEvent,
--wl.LAST_ACT_OUTCOME as LastActOutcome,
O3.OUTCOME_CODE as LastActivityOutcome,
--wl.LAST_ACT_TYPE as LastActType,
CASE WHEN TT.TRt_type is null  then OU.OUTCOME_CODE ELSE TT.TRt_type END as LastActivityType,
wl.LAST_EVENT_LOC as LastEventLoc,
wl.FU_ACTNOTEKEY as ActNotekeyFU,
wl.FU_TO_COME_IN_DATE as DateFUToComeIn,
wl.PLANNED_ASA_GRADE as PlannedASAGrade,
--wl.INTENDED_ADMIT_METHOD as IntendedAdmitMethod,
m2.method as AdmissionMethodIntended,
--wl.wLIST AS WaitingListType,
''EN'' as WaitingListType, 
wl.DOC_REFERENCE_NO AS DocumentReference,
wl.VIRTUAL_TYPE as VirtualType,
wl.CONSULT_METHOD as ConsultMethod,
wl.PREVIOUS_VIRTUAL_TYPE as PreviousVirtualType,
wl.PREVIOUS_CONSULT_METHOD as PreviousConsultMethod,
wl.PREF_VIRTUAL_TYPE as PreferredVirtualType,
wl.PREF_CONSULT_METHOD as PreferredConsultMethod,
wl.VIRTUAL_CONTACT_DETAILS as VirtualContactDetail,
wl.ELECTIVE_PRIORITY_LEVEL as ElectivePriorityLevel,
wl.REPRIORITISED_TAGET_DATE as DateReprioritisedTarget,
wl.ADMIT_METHOD AS AdmissionMethodRePrioritised,
cast(pathway_notes as varchar (3000)) as PathwayNote,
Null as DaysSuspension,
Null as DaysDNASuspension,
Null as DateDNA,
Null as DateLastPreOp,
Null as LastPreOpAttendanceStatus,
Null as DateConsultantChangeRefused,
Null as ListReviewStatus,
Null as TotalAdmissionOffers,
Null as DateAppointmentRescheduled,
Null as IntendedManagement,
Null as DateReferralRequestReceived,
Null as DateReferralSent,
Null as ReferralReason,
Null as LocalReferralUrgnc,
Null as LocalReferralPrity,
Null as DateLastSuspensionStart,
Null as DateLastSuspensionEnd,
Null as LastSuspensionReason,
Null as DateLastWaitingListReview,
Null as LastWaitingListReviewStatus,
Null as LastWaitingListReviewBatchNumber,
Null as EisQueryId,
Null as ElectiveAdmissionType,
Null as LocalWLType,
rep.priority_by as HCPRePrioritisedBy,
rep.priority_date as DateRePrioritised,
Null as PriorityClinical,
wl.DISCHARGE_DATE as DateDischargeOfLastAdmission,
wl.NEXT_APPT_NEEDED as NextApptNeeded,
null as DateDDTA

/*
r.CLIN_REF_DATE as ClinicalReferralDate,
TT.TRT_TYPE as TRT_TYPE2, 
ou.OUTCOME_CODE AS outcome_code2,
*/

	from 
	
		REF_WAIT_LEN_VIEW_ENH (''TO'',''01/01/2999'','''','''','''','''') as wl
		left join Refer R on WL.LinkID = R.LINKID
		left join coding c on c.linkid = wl.linkid and((c.itemno=1) or (c.itemno is null)) and c.when_coded = ''4'' and code_type =''OP''
		left join padloc on wl.loc = padloc.loccode
		left join GP2 on r.cons = gp2.practice
		left join TRT_TYPE TT ON TT.trt_DESCRIPTION = wl.LAST_act_type 
        left join OUTCOME OU ON OU.DESCRIPT = wl.LAST_act_type
		left join OUTCOME O3 ON O3.DESCRIPT = wl.LAST_act_OUTCOME
		left join ADMITMTH m2 on m2.description = wl.INTENDED_ADMIT_METHOD
		left join PATHWAYMGT pm ON pm.UPI = wl.RTT_UPI and (coalesce (pm.event_Source, ''PN'') = ''PN'' and pm.pwaykey = (select first 1 pm2.pwaykey from pathwaymgt pm2 where pm2.UPI = wl.RTT_UPI and coalesce(pm2.event_source, ''PN'') = ''PN''))
		left join REF_ELECTIVE_REPRIORITISED rep on rep.seqno = (select first 1 seqno from REF_ELECTIVE_REPRIORITISED r2 where r2.linkid = wl.linkid order by date_entered desc) 




'


) at [WPAS_Central];
END

---EXEC(' Select * from REF_WAIT_LEN_VIEW_ENH (''21'', ''23 JUN 2021'' ,'''','''','''','''') ') AT [WPAS_Central] 
-- REF_WAIT_LEN_VIEW_ENH (''''21'''',''''' + @TodayDateText + ''''','''''''','''''''','''''''','''''''') as wl


GO
