SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[Get_WAST_Data_PCR]

AS
BEGIN
	SET NOCOUNT ON;
	select
	      ABCD2
      ,ACCESS_ANTT
      ,ACCESS_IO
      ,ACCESS_IV
      ,ADX_PAED_1ST
      ,ADX_PAED_TOT
      ,ADX_STAFF
      ,ADX_TIME1
      ,ADX_TOTAL_ADULT
      ,AED_NONSHOCK
      ,AED_SHOCKABLE
      ,AET_ASPHYXIA
      ,AET_ELEC
      ,AET_MEDICAL
      ,AET_OVERDOSE
      ,AET_SUBMERSION
      ,AET_TRAUMA
      ,AGE
      ,AGE_MONTHS
      ,AIRBAG
      ,AIRWAY1_CLEAR
      ,AIRWAY1_OBSTRUCTED
      ,AIRWAY1_PARTIAL
      ,AIRWAY2_CLEAR
      ,AIRWAY2_OBSTRUCTED
      ,AIRWAY2_PARTIAL
      ,AIRWAY3_CLEAR
      ,AIRWAY3_OBSTRUCTED
      ,AIRWAY3_PARTIAL
      ,AIRWAY4_CLEAR
      ,AIRWAY4_OBSTRUCTED
      ,AIRWAY4_PARTIAL
      ,AMO_150MG
      ,AMO_300MG
      ,AMO_PAED_MG1
      ,AMO_PAED_MG2
      ,AMO_STAFF
      ,AMO_TIME1
      ,AMO_TIME2
      ,ASSISTED_VENT
      ,ASYSTOLE
      ,AtHospTimeClean
      ,ATRIAL_FIB
      ,AtSceneTimeClean
      ,ATTENDANT1
      ,ATTENDANT2
      ,ATTENDANT3
      ,ATTENDANT4
      ,ATTENDANT5
      ,ATTENDED_24HRS
      ,AVPU1_A
      ,AVPU1_P
      ,AVPU1_U
      ,AVPU1_V
      ,AVPU2_A
      ,AVPU2_P
      ,AVPU2_U
      ,AVPU2_V
      ,AVPU3_A
      ,AVPU3_P
      ,AVPU3_U
      ,AVPU3_V
      ,AVPU4_A
      ,AVPU4_P
      ,AVPU4_U
      ,AVPU4_V
      ,BASE1
      ,BASE2
      ,BASE3
      ,BASE4
      ,BASE5
	  ,billId
      ,BRADY_PAEDS
      ,BREATHING1_ABSENT
      ,BREATHING1_PRESENT
      ,BREATHING2_ABSENT
      ,BREATHING2_PRESENT
      ,BREATHING3_ABSENT
      ,BREATHING3_PRESENT
      ,BREATHING4_ABSENT
      ,BREATHING4_PRESENT
      ,BURNS_CHEM
      ,BURNS_ELEC
      ,BURNS_FLAME
      ,BURNS_OTHER
      ,BURNS_RULE9
      ,BURNS_SCALD
      ,BYST_COMP
      ,BYST_NO_SHOCK
      ,BYST_ROSC
      ,BYST_SHOCK
      ,BYST_VENT
      ,CALL_SIGN1
      ,CALL_SIGN2
      ,CALL_SIGN3
      ,Call999TimeClean
      ,CANNULA1
      ,CANNULA1_STAFF
      ,CANNULA2
      ,CANNULA2_STAFF
      ,CAP1_GREAT2
      ,CAP1_LESS2
      ,CAP2_GREAT2
      ,CAP2_LESS2
      ,CAP3_GREAT2
      ,CAP3_LESS2
      ,CAP4_GREAT2
      ,CAP4_LESS2
      ,CARF_ECG_12LEAD
      ,CARF_ETT_CHECK_AUSC
      ,CARF_ETT_CHECK_ETCO2
      ,CARF_ETT_ETCO2_MMHG
      ,CARF_ETT_STAFF
      ,CARF_GP_OOH
      ,CARF_MED1
      ,CARF_MED1_DOSE
      ,CARF_MED1_NAME
      ,CARF_MED1_ROUTE
      ,CARF_MED1_STAFF
      ,CARF_MED1_TIME
      ,CARF_MED1_UNIT
      ,CARF_MED2
      ,CARF_MED2_DOSE
      ,CARF_MED2_NAME
      ,CARF_MED2_ROUTE
      ,CARF_MED2_STAFF
      ,CARF_MED2_TIME
      ,CARF_MED2_UNIT
      ,CARF_MED3
      ,CARF_MED3_DOSE
      ,CARF_MED3_NAME
      ,CARF_MED3_ROUTE
      ,CARF_MED3_STAFF
      ,CARF_MED3_TIME
      ,CARF_MED3_UNIT
      ,CARF_MED4
      ,CARF_MED4_DOSE
      ,CARF_MED4_NAME
      ,CARF_MED4_ROUTE
      ,CARF_MED4_STAFF
      ,CARF_MED4_TIME
      ,CARF_MED4_UNIT
      ,CARF_NCRIC_STAFF
      ,CARF_NPA
      ,CARF_O2
      ,CARF_OPA
      ,CARF_POLICE
      ,CARF_SGA_STAFF
      ,CARF_STAFF
      ,CEASED_ED
      ,CEASED_GP
      ,CEASED_ROLE
      ,CFR_SHOCK
      ,CIRC1_ABSENT
      ,CIRC1_PRESENT
      ,CIRC2_ABSENT
      ,CIRC2_PRESENT
      ,CIRC3_ABSENT
      ,CIRC3_PRESENT
      ,CIRC4_ABSENT
      ,CIRC4_PRESENT
      ,COMPRESS_MAN
      ,COMPRESS_MECH
      ,COMPRESS_QUAL
      ,CON_CODE1
      ,CON_CODE2
      ,CON_MAIN
      ,Condition1Description
      ,Condition2Description
      ,ConditionMainDescription
      ,CPR_AT_HOSP
      ,CYCLIST
      ,DATE
      ,DEFIB_SUM_ELEC
      ,DEFIB_SUM_PRINT
      ,DELIVERED_ENROUTE
      ,DELIVERED_SCENE
      ,DIASTOLIC1
      ,DIASTOLIC2
      ,DIASTOLIC3
      ,DIASTOLIC4
      ,DISCHARGED_48HRS
      ,DOB
      ,DOBAgeDerived
      ,EA_RRV_SHOCK
      ,ECG_12LEAD
      ,ECG_3LEAD
      ,ENTONOX
      ,ETHNICITY
      ,ETT_CHECK_AUSC
      ,ETT_CHECK_ETCO2
      ,ETT_ETCO2_MMHG
      ,ETT_STAFF
      ,EUREKA
      ,FAST_ARM_L
      ,FAST_ARM_OK
      ,FAST_ARM_R
      ,FAST_FACE_L
      ,FAST_FACE_OK
      ,FAST_FACE_R
      ,FAST_SPEECH
      ,FAST_SPEECH_OK
      ,FEMALE
      ,FIRSTNAME
      ,ForenameClean
      ,FORMUNIQUE
      ,GCS1_EYES
      ,GCS1_MOTOR
      ,GCS1_TOTAL
      ,GCS1_VERB
      ,GCS2_EYES
      ,GCS2_MOTOR
      ,GCS2_TOTAL
      ,GCS2_VERB
      ,GCS3_EYES
      ,GCS3_MOTOR
      ,GCS3_TOTAL
      ,GCS3_VERB
      ,GCS4_EYES
      ,GCS4_MOTOR
      ,GCS4_TOTAL
      ,GCS4_VERB
      ,GeographyKey
      ,GEST_AGE
      ,GLUCOSE1
      ,GLUCOSE2
      ,GLUCOSE3
      ,GLUCOSE4
      ,GRADE1
      ,GRADE2
      ,GRADE3
      ,GRADE4
      ,GRADE5
      ,HITS_H
      ,HITS_I
      ,HITS_NEG
      ,HITS_NONE
      ,HITS_S
      ,HITS_T
      ,HOSPITAL
      ,HospitalCodeClean
      ,HOT_UPGRADE
      ,INC_CCC
      ,INC_NO
      ,INFORMAL_CARE
      ,LANGUAGE_BSL
      ,LANGUAGE_ENGLISH
      ,LANGUAGE_OTHER
      ,LANGUAGE_WELSH
      ,LEAD_1
      ,LEAD_2
      ,LEAD_3
      ,LEAD_AVF
      ,LEAD_AVL
      ,LEAD_AVR
      ,LEAD_V1
      ,LEAD_V2
      ,LEAD_V3
      ,LEAD_V4
      ,LEAD_V5
      ,LEAD_V6
      ,LOC_HOME
      ,LOC_NHOME
      ,LOC_OTHER
      ,LOC_PUBLIC
      ,LOC_STREET
      ,LOW_ACUITY_TX
      ,MALE
      ,MCA_CAPACITY
      ,MCA_COMM_N
      ,MCA_COMM_Y
      ,MCA_LACK
      ,MCA_RETAIN_N
      ,MCA_RETAIN_Y
      ,MCA_STAFF
      ,MCA_UNDERSTAND_N
      ,MCA_UNDERSTAND_Y
      ,MCA_USE_N
      ,MCA_USE_Y
      ,MED1
      ,MED1_DOSE
      ,MED1_NAME
      ,MED1_ROUTE
      ,MED1_STAFF
      ,MED1_TIME
      ,MED1_UNIT
      ,MED2
      ,MED2_DOSE
      ,MED2_NAME
      ,MED2_ROUTE
      ,MED2_STAFF
      ,MED2_TIME
      ,MED2_UNIT
      ,MED3
      ,MED3_DOSE
      ,MED3_NAME
      ,MED3_ROUTE
      ,MED3_STAFF
      ,MED3_TIME
      ,MED3_UNIT
      ,MED4
      ,MED4_DOSE
      ,MED4_NAME
      ,MED4_ROUTE
      ,MED4_STAFF
      ,MED4_TIME
      ,MED4_UNIT
      ,MED5
      ,MED5_DOSE
      ,MED5_NAME
      ,MED5_ROUTE
      ,MED5_STAFF
      ,MED5_TIME
      ,MED5_UNIT
      ,MED6
      ,MED6_DOSE
      ,MED6_NAME
      ,MED6_ROUTE
      ,MED6_STAFF
      ,MED6_TIME
      ,MED6_UNIT
      ,MED7
      ,MED7_DOSE
      ,MED7_NAME
      ,MED7_ROUTE
      ,MED7_STAFF
      ,MED7_TIME
      ,MED7_UNIT
      ,MED8
      ,MED8_DOSE
      ,MED8_NAME
      ,MED8_ROUTE
      ,MED8_STAFF
      ,MED8_TIME
      ,MED8_UNIT
      ,MOTORBIKE
      ,NARRATIVE
      ,NC_ASSESS
      ,NC_EXAM
      ,NC_STAFF
      ,NC_TIME_PCR_SIGN
      ,NC_TREAT
      ,NC1_REFUSED
      ,NC2_REFER
      ,NC2_REFER_CCC
      ,NC2_REFER_EMS
      ,NC2_REFER_GP
      ,NC2_REFER_WAST
      ,NC3_OWN
      ,NC4_CARED_FOR
      ,NC5_LACK_ALT_PATHWAY
      ,NC5_LACK_CARED_FOR
      ,NC5_LACK_NO_HOSP
      ,NC5_LACK_REFER
      ,NCD_STAFF
      ,NCRIC_STAFF
      ,NEWS1_AVPU
      ,NEWS1_O2
      ,NEWS1_PULSE
      ,NEWS1_RESPS
      ,NEWS1_SPO2
      ,NEWS1_SYSTOLIC
      ,NEWS1_TEMP
      ,NEWS1_TOTAL
      ,NEWS2_AVPU
      ,NEWS2_O2
      ,NEWS2_PULSE
      ,NEWS2_RESPS
      ,NEWS2_SPO2
      ,NEWS2_SYSTOLIC
      ,NEWS2_TEMP
      ,NEWS2_TOTAL
      ,NEWS3_AVPU
      ,NEWS3_O2
      ,NEWS3_PULSE
      ,NEWS3_RESPS
      ,NEWS3_SPO2
      ,NEWS3_SYSTOLIC
      ,NEWS3_TEMP
      ,NEWS3_TOTAL
      ,NEWS4_AVPU
      ,NEWS4_O2
      ,NEWS4_PULSE
      ,NEWS4_RESPS
      ,NEWS4_SPO2
      ,NEWS4_SYSTOLIC
      ,NEWS4_TEMP
      ,NEWS4_TOTAL
      ,NHSNo
      ,NHSNoMatchProbability
      ,NHSNoStatus
      ,NO_WITNESS
      ,NPA
      ,NSR
      ,O2_MASK100
      ,O2_NASAL
      ,O2_PPV
      ,O2_SIMPLE
      ,O2_TRACH
      ,OBS1_SPO2
      ,OBS1_SPO2_AIR
      ,OBS1_SPO2_O2
      ,OBS1_STAFF
      ,OBS1_TIME
      ,OBS2_SPO2
      ,OBS2_SPO2_AIR
      ,OBS2_SPO2_O2
      ,OBS2_STAFF
      ,OBS2_TIME
      ,OBS3_SPO2
      ,OBS3_SPO2_AIR
      ,OBS3_SPO2_O2
      ,OBS3_STAFF
      ,OBS3_TIME
      ,OBS4_SPO2
      ,OBS4_SPO2_AIR
      ,OBS4_SPO2_O2
      ,OBS4_STAFF
      ,OBS4_TIME
      ,OPA
      ,OTHER_SHOCK
      ,PADS_SHOCK
      ,PAIN1
      ,PAIN2
      ,PAIN3
      ,PAIN4
      ,PCR
      ,PCR2
      ,PEA
      ,PEAK_FLOW1
      ,PEAK_FLOW2
      ,PEAK_FLOW3
      ,PEAK_FLOW4
      ,PEARL1_LEFT_DIL
      ,PEARL1_LEFT_PIN
      ,PEARL1_LEFT_REAC
      ,PEARL1_RIGHT_DIL
      ,PEARL1_RIGHT_PIN
      ,PEARL1_RIGHT_REAC
      ,PEARL2_LEFT_DIL
      ,PEARL2_LEFT_PIN
      ,PEARL2_LEFT_REAC
      ,PEARL2_RIGHT_DIL
      ,PEARL2_RIGHT_PIN
      ,PEARL2_RIGHT_REAC
      ,PEARL3_LEFT_DIL
      ,PEARL3_LEFT_PIN
      ,PEARL3_LEFT_REAC
      ,PEARL3_RIGHT_DIL
      ,PEARL3_RIGHT_PIN
      ,PEARL3_RIGHT_REAC
      ,PEARL4_LEFT_DIL
      ,PEARL4_LEFT_PIN
      ,PEARL4_LEFT_REAC
      ,PEARL4_RIGHT_DIL
      ,PEARL4_RIGHT_PIN
      ,PEARL4_RIGHT_REAC
      ,PEDESTRIAN
      ,PersonID
      ,PHT
      ,POSTCODE
      ,PostcodeClean
      ,PP_EXCL_AAA
      ,PP_EXCL_CHEST_PAIN
      ,PP_EXCL_CVA
      ,PP_EXCL_END_LIFE
      ,PP_EXCL_LESS16
      ,PP_EXCL_MENTAL
      ,PP_EXCL_NEWS
      ,PP_EXCL_OBGYN
      ,PP_EXCL_OD
      ,PP_MP_ABDO_PAIN
      ,PP_MP_AIRWAY
      ,PP_MP_BLEED
      ,PP_MP_BREATHING
      ,PP_MP_CARDIAC_HX
      ,PP_MP_COMPROM
      ,PP_MP_HAEMATEMESIS
      ,PP_MP_HAEMATURIA
      ,PP_MP_HEADACHE
      ,PP_MP_HX_HAEMATEMESIS
      ,PP_MP_HX_UNCON
      ,PP_MP_HYPERGLYC
      ,PP_MP_NEURO_HX
      ,PP_MP_NO_WALK
      ,PP_MP_NO_WEIGHT_BEAR
      ,PP_MP_NOT_ALERT
      ,PP_MP_OEDEMA
      ,PP_MP_OUCH
      ,PP_MP_PR_BLEED
      ,PP_MP_PULSE_ABNORMAL
      ,PP_MP_PYREXIA
      ,PP_MP_RASH
      ,PP_MP_RETENTION
      ,PP_MP_SHOCK
      ,PP_MP_TACHY
      ,PP_MP_TEMP_ABNORMAL
      ,PP_MP_VERTIGO
      ,PP_OUT_ACS
      ,PP_OUT_ADVICE
      ,PP_OUT_AMBER
      ,PP_OUT_BLUE
      ,PP_OUT_CCP
      ,PP_OUT_EA_EMT
      ,PP_OUT_EA_PARAMEDIC
      ,PP_OUT_ED
      ,PP_OUT_EPILEPSY
      ,PP_OUT_GP
      ,PP_OUT_HYPOGLYCAEMIA
      ,PP_OUT_INFO
      ,PP_OUT_LGH
      ,PP_OUT_MAU
      ,PP_OUT_MED
      ,PP_OUT_NI_FALL
      ,PP_OUT_NOT_ACCEPTED
      ,PP_OUT_OOH
      ,PP_OUT_OWN_CAR
      ,PP_OUT_PCS
      ,PP_OUT_PT_PATHWAY
      ,PP_OUT_PT_REFUSAL
      ,PP_OUT_RED
      ,PP_OUT_SUCCESS
      ,PP_OUT_TAXI
      ,PP_OUT_TRAUMA
      ,PP_OUT_UCS
      ,PP_OUT_UNAVAIL
      ,PP_STAFF
      ,PP_TP_AIRWAY
      ,PP_TP_BLEED
      ,PP_TP_BREATHING
      ,PP_TP_COMPROM
      ,PP_TP_DEFORMITY
      ,PP_TP_ELEC_CHEM
      ,PP_TP_HEAD_INJURY
      ,PP_TP_HX_UNCON
      ,PP_TP_INHALATION
      ,PP_TP_MOI
      ,PP_TP_NECK_BACK
      ,PP_TP_NEURO
      ,PP_TP_NO_WALK
      ,PP_TP_NOT_ALERT
      ,PP_TP_OEDEMA
      ,PP_TP_OUCH
      ,PP_TP_PENETRATE
      ,PP_TP_SHOCK
      ,PP_TP_SKIN
      ,PP_TP_TEMP_HYPO
      ,PPCI_REF
      ,PRE_ALERT
      ,PULSE1
      ,PULSE2
      ,PULSE3
      ,PULSE4
      ,R_I
      ,R_I_INFO
      ,RESP_RATE1
      ,RESP_RATE2
      ,RESP_RATE3
      ,RESP_RATE4
      ,ROLE_DATE
      ,ROLE_SIG
      ,ROLE_TIME
      ,ROLE1_0CPR
      ,ROLE1_15MIN
      ,ROLE1_ASYS_30S
      ,ROLE1_NO_EXCL
      ,ROLE1_SUB
      ,ROLE2_ALS
      ,ROLE3_CRANIAL
      ,ROLE3_DECAP
      ,ROLE3_DECOMP
      ,ROLE3_HEMICORP
      ,ROLE3_HYPOSTASIS
      ,ROLE3_INCIN
      ,ROLE3_MACER
      ,ROLE3_RIGOR
      ,ROLE4_DNACPR
      ,ROLE4_LWILL
      ,ROLE4_TERMINAL
      ,ROSC_ANY_TIME
      ,ROSC_AT_HOSP
      ,RTC_EJECT
      ,RTC_SELF_EXT
      ,RTC_TRAP_MINS
      ,SAFEGUARD
      ,SAFEGUARD_ADULT
      ,SAFEGUARD_CHILD
      ,SAFEGUARD_STAFF
      ,SEATBELT_HELMET
      ,SexDerived
      ,SGA_STAFF
      ,SPEED_10TO30
      ,SPEED_GREAT30
      ,SPEED_LESS10
      ,SPINAL_BOARD
      ,SPINAL_COLLAR
      ,SPINAL_KED
      ,SPINAL_VACUUM
      ,STAFF1
      ,STAFF2
      ,STAFF3
      ,STAFF4
      ,STAFF5
      ,StatsCurrentCensusHealthOrganisationCode
      ,StatsCurrentCensusHealthOrganisationName
      ,StatsCurrentCensusLocalAuthorityCode
      ,StatsCurrentCensusLocalAuthorityName
      ,StatsCurrentCensusLowerSuperOutputAreaCode
      ,STEMI
      ,STROKE_UNIT
      ,SURNAME
      ,SYSTOLIC1
      ,SYSTOLIC2
      ,SYSTOLIC3
      ,SYSTOLIC4
      ,TEMP1
      ,TEMP2
      ,TEMP3
      ,TEMP4
      ,THUMP
      ,TIA_CLINIC
      ,TIME_1ST_ROSC
      ,TIME_999
      ,TIME_AT_HOSP
      ,TIME_AT_PATIENTS_SIDE
      ,TIME_AT_SCENE
      ,TIME_CEASED
      ,TIME_CFR_HANDOVER
      ,TIME_COLLAPSE
      ,TIME_CORD_CUT
      ,TIME_DELIVERED
      ,TIME_ONSET_SYMPTOMS
      ,TIME_PLACENTA
      ,TIME_RRV_HANDOVER
      ,TIME_SHOCK
      ,TIME_STROKE_ONSET
      ,TOTAL_SHOCKS
      ,TRAUMA_ASSAULT
      ,TRAUMA_BLAST
      ,TRAUMA_BLUNT
      ,TRAUMA_ELEC
      ,TRAUMA_FALL_HI
      ,TRAUMA_FALL_LO
      ,TRAUMA_FIREARMS
      ,TRAUMA_OTHER
      ,TRAUMA_PENETRATE
      ,VEHICLE_OCCUPANT
      ,VF
      ,VT
      ,WITNESS_BYSTANDER
      ,WITNESS_EMS


  FROM    [7A1A1SRVINFONDR].[WAST].[dbo].[PCR]

End
GO
