SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[Get_UnscheduledCare_Data_EDAttendanceCentral]
	
AS
BEGIN
	
	SET NOCOUNT ON;

	--DECLARE @LastAttendanceDate AS VARCHAR(30) = '17 July 2021'
   	DECLARE @LastAttendanceDate AS DATE = (SELECT ISNULL(MAX(ArrivalDate),'31 December 2010') FROM [Foundation].[dbo].[UnscheduledCare_Data_EDAttendance] WHERE Area='Central')
	DECLARE @LastAttendanceDateString AS VARCHAR(30) = DATENAME(DAY,@LastAttendanceDate) + ' ' + DATENAME(MONTH,@LastAttendanceDate) + ' ' + DATENAME(YEAR,@LastAttendanceDate)
	DECLARE @DateToString AS VARCHAR(30) = DATENAME(DAY,GETDATE()) + ' ' + DATENAME(MONTH,GETDATE()) + ' ' + DATENAME(YEAR,GETDATE())
	--DECLARE @DateToString AS VARCHAR(30) = '19 July 2021'


	EXEC('
		SELECT DISTINCT
			''Central'' AS Area,
			''WPAS'' AS Source,
			ED.LINKID AS AttendanceIdentifier,
			T.CASENO AS LocalPatientIdentifier,
			NULLIF(P.NHS,'''') AS NHSNumber,
			--NULLIF(T.REG_GP,'''') AS RegisteredGP,
			--NULLIF(T.REG_PRAC,'''') AS RegisteredPractice,
			NULLIF(T.GP_TRT,'''') AS RegisteredGP,
			NULLIF(T.GP_PRAC,'''') AS RegisteredPractice,
			NULLIF(T.POSTCODE,'''') AS PatientPostcode,
			NULLIF(T.DHA_CODE,'''') AS DHA,
			R.GP_REF AS ReferringGP,
			R.GP_PRAC AS ReferringPractice,
			ED.ILLNESS_START_DATE AS IncidentDate,
			CASE
				WHEN ED.ILLNESS_START_DATE IS NULL THEN NULL
				WHEN TRIM(ED.ILLNESS_START_TIME)='':'' THEN ''00:00''
				WHEN ED.ILLNESS_START_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.ILLNESS_START_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.ILLNESS_START_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.ILLNESS_START_TIME FROM 3 FOR 2) 
			END AS IncidentTime,
			ED.ARRIVAL_DATE AS ArrivalDate,
			CASE
				WHEN ED.ARRIVAL_DATE IS NULL THEN NULL
				WHEN TRIM(ED.ARRIVAL_TIME)='':'' THEN ''00:00''
				WHEN ED.ARRIVAL_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.ARRIVAL_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.ARRIVAL_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.ARRIVAL_TIME FROM 3 FOR 2) 
			END AS ArrivalTime,
			CAST(ED.AMBULANCE_HANDOVER AS DATE) AS AmbulanceHandoverDate,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM ED.AMBULANCE_HANDOVER) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM ED.AMBULANCE_HANDOVER) AS VARCHAR(2)),2) AS AmbulanceHandoverTime,
			ED.REGISTERED_DATE AS RegisteredDate,
			CASE
				WHEN ED.REGISTERED_DATE IS NULL THEN NULL
				WHEN TRIM(ED.REGISTERED_TIME)='':'' THEN ''00:00''
				WHEN ED.REGISTERED_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.REGISTERED_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.REGISTERED_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.REGISTERED_TIME FROM 3 FOR 2) 
			END AS RegisteredTime,
			ED.TRIAGE_DATE AS TriageStartDate,
			CASE
				WHEN ED.TRIAGE_DATE IS NULL THEN NULL
				WHEN TRIM(ED.TRIAGE_TIME)='':'' THEN ''00:00''
				WHEN ED.TRIAGE_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.TRIAGE_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.TRIAGE_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.TRIAGE_TIME FROM 3 FOR 2) 
			END AS TriageStartTime,
			NULL AS TriageEndDate,
			NULL AS TriageEndTime,
			--REPLACED WITH SAME VALUES AS TREATMENTSTART BY MP AT REQUEST OF CR - SEE EMAIL CONVERSATION WITH CR SEPT 2021 FOR DETAILS
			--NULL AS EDClinicianSeenDate,
			--NULL AS EDClinicianSeenTime,
			ED.TREATMENT_DATE AS EDClinicianSeenDate,
			CASE
				WHEN ED.TREATMENT_DATE IS NULL THEN NULL
				WHEN TRIM(ED.TREATMENT_TIME)='':'' THEN ''00:00''
				WHEN ED.TREATMENT_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.TREATMENT_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.TREATMENT_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.TREATMENT_TIME FROM 3 FOR 2) 
			END AS EDClinicianSeenTime,
			ED.TREATMENT_DATE AS TreatmentStartDate,
			CASE
				WHEN ED.TREATMENT_DATE IS NULL THEN NULL
				WHEN TRIM(ED.TREATMENT_TIME)='':'' THEN ''00:00''
				WHEN ED.TREATMENT_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.TREATMENT_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.TREATMENT_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.TREATMENT_TIME FROM 3 FOR 2) 
			END AS TreatmentStartTime,
			ED.TREATMENT_COMPLETE AS TreatmentCompleteDate,
			CASE
				WHEN ED.TREATMENT_COMPLETE IS NULL THEN NULL
				WHEN TRIM(ED.TREATMENT_COMPLETE_AT)='':'' THEN ''00:00''
				WHEN ED.TREATMENT_COMPLETE_AT IS NULL THEN ''00:00''
				WHEN TRIM(ED.TREATMENT_COMPLETE_AT)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.TREATMENT_COMPLETE_AT FROM 1 FOR 2)||'':''||SUBSTRING(ED.TREATMENT_COMPLETE_AT FROM 3 FOR 2) 
			END AS TreatmentCompleteTime,
			ED.DECISION_TO_ADMIT_DATE AS DecisionToAdmitDate,
			CASE
				WHEN ED.DECISION_TO_ADMIT_DATE IS NULL THEN NULL
				WHEN TRIM(ED.DECISION_TO_ADMIT_TIME)='':'' THEN ''00:00''
				WHEN ED.DECISION_TO_ADMIT_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.DECISION_TO_ADMIT_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.DECISION_TO_ADMIT_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.DECISION_TO_ADMIT_TIME FROM 3 FOR 2) 
			END AS DecisionToAdmitTime,
			--CAST(BH.BREACH_END AS DATE) AS BreachEndDate,
			--RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH.BREACH_END) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH.BREACH_END) AS VARCHAR(2)),2) AS BreachEndTime,
			ED.DISCHARGE_DATE AS DischargeDate,
			CASE
				WHEN ED.DISCHARGE_DATE IS NULL THEN NULL
				WHEN TRIM(ED.DISCHARGE_TIME)='':'' THEN ''00:00''
				WHEN ED.DISCHARGE_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.DISCHARGE_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.DISCHARGE_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.DISCHARGE_TIME FROM 3 FOR 2) 
			END AS DischargeTime,
			ED.DISCHARGE_DATE AS DepartureDate,
			CASE
				WHEN ED.DISCHARGE_DATE IS NULL THEN NULL
				WHEN TRIM(ED.DISCHARGE_TIME)='':'' THEN ''00:00''
				WHEN ED.DISCHARGE_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.DISCHARGE_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.DISCHARGE_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.DISCHARGE_TIME FROM 3 FOR 2) 
			END AS DepartureTime,
			--ED.CLINICIAN_REQUEST_DATE AS ConsultationRequestDate,
			--CASE
			--	WHEN ED.CLINICIAN_REQUEST_DATE IS NULL THEN NULL
			--	WHEN TRIM(ED.CLINICIAN_REQUEST_TIME)='':'' THEN ''00:00''
			--	WHEN ED.CLINICIAN_REQUEST_TIME IS NULL THEN ''00:00''
			--	WHEN TRIM(ED.CLINICIAN_REQUEST_TIME)='''' THEN ''00:00''
			--	ELSE SUBSTRING(ED.CLINICIAN_REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.CLINICIAN_REQUEST_TIME FROM 3 FOR 2) 
			--END AS ConsultationRequestTime,
			--ED.CLINICIAN_SERVICE_DATE AS ConsultationResponseDate,
			--CASE
			--	WHEN ED.CLINICIAN_SERVICE_DATE IS NULL THEN NULL
			--	WHEN TRIM(ED.CLINICIAN_SERVICE_TIME)='':'' THEN ''00:00''
			--	WHEN ED.CLINICIAN_SERVICE_TIME IS NULL THEN ''00:00''
			--	WHEN TRIM(ED.CLINICIAN_SERVICE_TIME)='''' THEN ''00:00''
			--	ELSE SUBSTRING(ED.CLINICIAN_SERVICE_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.CLINICIAN_SERVICE_TIME FROM 3 FOR 2) 
			--END AS ConsultationResponseTime,
			ED.TRANSPORT_REQUESTED_AT AS TransportRequestedDate,
			CASE
				WHEN ED.TRANSPORT_REQUESTED_AT IS NULL THEN NULL
				WHEN TRIM(ED.TRANSPORT_REQUESTED_TIME)='':'' THEN ''00:00''
				WHEN ED.TRANSPORT_REQUESTED_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.TRANSPORT_REQUESTED_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.TRANSPORT_REQUESTED_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.TRANSPORT_REQUESTED_TIME FROM 3 FOR 2) 
			END AS TransportRequestedTime,
			ED.TRANSPORT_ARRIVED_AT AS TransportArrivedDate,
			CASE
				WHEN ED.TRANSPORT_ARRIVED_AT IS NULL THEN NULL
				WHEN TRIM(ED.TRANSPORT_ARRIVED_TIME)='':'' THEN ''00:00''
				WHEN ED.TRANSPORT_ARRIVED_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.TRANSPORT_ARRIVED_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.TRANSPORT_ARRIVED_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.TRANSPORT_ARRIVED_TIME FROM 3 FOR 2) 
			END AS TransportArrivedTime,
			ED.BED_REQUESTED_AT AS BedRequestedDate,
			CASE
				WHEN ED.BED_REQUESTED_AT IS NULL THEN NULL
				WHEN TRIM(ED.BED_REQUESTED_TIME)='':'' THEN ''00:00''
				WHEN ED.BED_REQUESTED_TIME IS NULL THEN ''00:00''
				WHEN TRIM(ED.BED_REQUESTED_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(ED.BED_REQUESTED_TIME FROM 1 FOR 2)||'':''||SUBSTRING(ED.BED_REQUESTED_TIME FROM 3 FOR 2) 
			END AS BedRequestedTime,
			NULL AS BedRequestedOutcomeDate,
			NULL AS BedRequestedOutcomeTime,
			NULLIF(ED.AMBULANCE_PCO,'''') AS AmbulanceReference,
			PADLOC.BELONGS_TO AS SiteCodeOfTreatment,
			NULLIF(ED.PATIENT_COMPLAINT,'''') AS PresentingComplaint,
			ED.PATIENT_SENTBY AS ReferralSource,
			ED.PATIENT_ARRIVEDBY AS ArrivalMode,
			ED.PATIENT_REASON AS PatientGroup,
			ED.PATIENT_ACCOMPANIED_BY_1 AS AccompaniedBy1,
			ED.PATIENT_ACCOMPANIED_BY_2 AS AccompaniedBy2,
			ED.PATIENT_WHERE AS IncidentLocation,
			--CASE
			--	WHEN ED.PATIENT_REASON IN (''RTA'',''RTC'') THEN ED.PATIENT_REASON
			--	ELSE ED.PATIENT_WHAT_DOING 
			--END AS IncidentActivity,
			ED.PATIENT_WHAT_DOING AS IncidentActivity,
			--ED.TRIAGE_TREATMENT AS TriageCategory,
			CASE 
				--WHEN ED.SEE_AND_TREAT=''Y'' THEN ''06''
				WHEN ED.REGISTERED_DATE >=''25 SEPTEMBER 2017'' THEN
					CASE
						WHEN TD.DISCRIMINATOR_ID IS NOT NULL THEN CAST(TD.DISCRIMINATOR_LEVEL AS INT)
						ELSE ED.TRIAGE_TREATMENT
					END
				ELSE ED.TRIAGE_TREATMENT
			END AS TriageCategory,
			NULL AS TriageComplaint,
			NULL AS TriageTreatment,
			NULL AS TriageTreatment1,
			NULL AS TriageTreatment2,
			NULL AS TriageTreatment3,
			NULL AS TriageTreatment4,
			NULL AS TriageTreatment5,
			NULL AS TriageTreatment6,
			NULL AS TriageTreatment7,
			NULL AS TriageTreatment8,
			NULL AS TriageTreatment9,
			NULL AS TriageTreatment10,
			ED.DISCRIMINATOR_ID AS TriageDiscriminator,
			ED.PATIENT_IMMUNISATION AS Immunisation,
			NULLIF(ED.PATIENT_SCHOOL,'''') AS School,
			ED.PATIENT_DISPOSAL AS DischargeOutcome,
			ED.DISCHARGE_DESTINATION AS DischargeDestination,

			CASE
				WHEN ED.PATIENT_REASON IN (''RES'',''REU'') THEN ''04''
				ELSE ED.ALCOHOL 
			END AS AlcoholRelated,
			
			ED.PATIENT_HOW_LONG AS TimeSinceIncident,
			NULLIF(ED.BED_WARD_SENTTO,'''') AS BedRequestedWard,
			NULLIF(ED.BED_CONSULTANT,'''') AS BedRequestedConsultant,
			NULLIF(ED.BED_SPECIALTY,'''') AS BedRequestedSpecialty,
			NULL AS BedRequestedOutcome,
			NULLIF(ED.TREATMENT_BY,'''') AS EDClinicianSeen,
			--NULLIF(EDCS.GP_CODE,'''') AS EDClinicianSeen,
			ED.SEE_AND_TREAT AS SeeAndTreat,

			CASE
				WHEN ED.PATIENT_REASON=''RES'' THEN ''02''
				WHEN ED.PATIENT_REASON=''REU'' THEN ''03''
				ELSE ''01''
			END AS AttendanceCategory,

			CASE
				WHEN ED.PATIENT_REASON=''RES'' THEN ''03''
				WHEN ED.PATIENT_SENTBY=''PRIME'' THEN ''02''
				ELSE ''01''
			END AS AppropriateAttendance,
			
			CASE
				WHEN LEFT(ED.PATIENT_REASON,2)=''RT'' THEN ''99''
				ELSE ''98''
			END AS RTAPatientType,
			ED.PATIENT_REASON AS MechanismOfInjury,
			D1.THECODE AS Diagnosis1DiagnosisType,
			D1.REQUEST_DATE AS Diagnosis1DiagnosisDate,
			CASE
				WHEN D1.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(D1.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN D1.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(D1.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(D1.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(D1.REQUEST_TIME FROM 3 FOR 2) 
			END AS Diagnosis1DiagnosisTime,
			NULLIF(D1.REQUEST_SITE,'''') AS Diagnosis1DiagnosisSite,
			NULLIF(D1.REQUEST_SIDE,'''') AS Diagnosis1DiagnosisSide,
			D2.THECODE AS Diagnosis2DiagnosisType,
			D2.REQUEST_DATE AS Diagnosis2DiagnosisDate,
			CASE
				WHEN D2.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(D2.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN D2.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(D2.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(D2.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(D2.REQUEST_TIME FROM 3 FOR 2) 
			END AS Diagnosis2DiagnosisTime,
			NULLIF(D2.REQUEST_SITE,'''') AS Diagnosis2DiagnosisSite,
			NULLIF(D2.REQUEST_SIDE,'''') AS Diagnosis2DiagnosisSide,
			D3.THECODE AS Diagnosis3DiagnosisType,
			D3.REQUEST_DATE AS Diagnosis3DiagnosisDate,
			CASE
				WHEN D3.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(D3.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN D3.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(D3.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(D3.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(D3.REQUEST_TIME FROM 3 FOR 2) 
			END AS Diagnosis3DiagnosisTime,
			NULLIF(D3.REQUEST_SITE,'''') AS Diagnosis3DiagnosisSite,
			NULLIF(D3.REQUEST_SIDE,'''') AS Diagnosis3DiagnosisSide,
			D4.THECODE AS Diagnosis4DiagnosisType,
			D4.REQUEST_DATE AS Diagnosis4DiagnosisDate,
			CASE
				WHEN D4.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(D4.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN D4.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(D4.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(D4.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(D4.REQUEST_TIME FROM 3 FOR 2) 
			END AS Diagnosis4DiagnosisTime,
			NULLIF(D4.REQUEST_SITE,'''') AS Diagnosis4DiagnosisSite,
			NULLIF(D4.REQUEST_SIDE,'''') AS Diagnosis4DiagnosisSide,
			D5.THECODE AS Diagnosis5DiagnosisType,
			D5.REQUEST_DATE AS Diagnosis5DiagnosisDate,
			CASE
				WHEN D5.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(D5.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN D5.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(D5.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(D5.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(D5.REQUEST_TIME FROM 3 FOR 2) 
			END AS Diagnosis5DiagnosisTime,
			NULLIF(D5.REQUEST_SITE,'''') AS Diagnosis5DiagnosisSite,
			NULLIF(D5.REQUEST_SIDE,'''') AS Diagnosis5DiagnosisSide,
			D6.THECODE AS Diagnosis6DiagnosisType,
			D6.REQUEST_DATE AS Diagnosis6DiagnosisDate,
			CASE
				WHEN D6.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(D6.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN D6.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(D6.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(D6.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(D6.REQUEST_TIME FROM 3 FOR 2) 
			END AS Diagnosis6DiagnosisTime,
			NULLIF(D6.REQUEST_SITE,'''') AS Diagnosis6DiagnosisSite,
			NULLIF(D6.REQUEST_SIDE,'''') AS Diagnosis6DiagnosisSide,
			X1.THECODE AS Xray1RequestType,
			X1.REQUEST_DATE AS Xray1RequestDate,
			CASE
				WHEN X1.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(X1.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN X1.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(X1.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(X1.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(X1.REQUEST_TIME FROM 3 FOR 2) 
			END AS Xray1RequestTime,
			X1.REQUEST_SITE AS Xray1RequestSite,
			X1.REQUEST_SIDE AS Xray1RequestSide,
			X2.THECODE AS Xray2RequestType,
			X2.REQUEST_DATE AS Xray2RequestDate,
			CASE
				WHEN X2.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(X2.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN X2.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(X2.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(X2.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(X2.REQUEST_TIME FROM 3 FOR 2) 
			END AS Xray2RequestTime,
			X2.REQUEST_SITE AS Xray2RequestSite,
			X2.REQUEST_SIDE AS Xray2RequestSide,
			X3.THECODE AS Xray3RequestType,
			X3.REQUEST_DATE AS Xray3RequestDate,
			CASE
				WHEN X3.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(X3.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN X3.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(X3.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(X3.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(X3.REQUEST_TIME FROM 3 FOR 2) 
			END AS Xray3RequestTime,
			X3.REQUEST_SITE AS Xray3RequestSite,
			X3.REQUEST_SIDE AS Xray3RequestSide,
			X4.THECODE AS Xray4RequestType,
			X4.REQUEST_DATE AS Xray4RequestDate,
			CASE
				WHEN X4.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(X4.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN X4.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(X4.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(X4.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(X4.REQUEST_TIME FROM 3 FOR 2) 
			END AS Xray4RequestTime,
			X4.REQUEST_SITE AS Xray4RequestSite,
			X4.REQUEST_SIDE AS Xray4RequestSide,
			X5.THECODE AS Xray5RequestType,
			X5.REQUEST_DATE AS Xray5RequestDate,
			CASE
				WHEN X5.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(X5.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN X5.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(X5.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(X5.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(X5.REQUEST_TIME FROM 3 FOR 2) 
			END AS Xray5RequestTime,
			X5.REQUEST_SITE AS Xray5RequestSite,
			X5.REQUEST_SIDE AS Xray5RequestSide,
			X6.THECODE AS Xray6RequestType,
			X6.REQUEST_DATE AS Xray6RequestDate,
			CASE
				WHEN X6.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(X6.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN X6.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(X6.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(X6.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(X6.REQUEST_TIME FROM 3 FOR 2) 
			END AS Xray6RequestTime,
			X6.REQUEST_SITE AS Xray6RequestSite,
			X6.REQUEST_SIDE AS Xray6RequestSide,
			I1.THECODE AS Investigation1RequestType,
			I1.REQUEST_DATE AS Investigation1RequestDate,
			CASE
				WHEN I1.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(I1.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN I1.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(I1.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(I1.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(I1.REQUEST_TIME FROM 3 FOR 2) 
			END AS Investigation1RequestTime,
			I2.THECODE AS Investigation2RequestType,
			I2.REQUEST_DATE AS Investigation2RequestDate,
			CASE
				WHEN I2.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(I2.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN I2.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(I2.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(I2.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(I2.REQUEST_TIME FROM 3 FOR 2) 
			END AS Investigation2RequestTime,
			I3.THECODE AS Investigation3RequestType,
			I3.REQUEST_DATE AS Investigation3RequestDate,
			CASE
				WHEN I3.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(I3.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN I3.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(I3.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(I3.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(I3.REQUEST_TIME FROM 3 FOR 2) 
			END AS Investigation3RequestTime,
			I4.THECODE AS Investigation4RequestType,
			I4.REQUEST_DATE AS Investigation4RequestDate,
			CASE
				WHEN I4.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(I4.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN I4.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(I4.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(I4.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(I4.REQUEST_TIME FROM 3 FOR 2) 
			END AS Investigation4RequestTime,
			I5.THECODE AS Investigation5RequestType,
			I5.REQUEST_DATE AS Investigation5RequestDate,
			CASE
				WHEN I5.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(I5.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN I5.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(I5.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(I5.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(I5.REQUEST_TIME FROM 3 FOR 2) 
			END AS Investigation5RequestTime,
			I6.THECODE AS Investigation6RequestType,
			I6.REQUEST_DATE AS Investigation6RequestDate,
			CASE
				WHEN I6.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(I6.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN I6.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(I6.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(I6.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(I6.REQUEST_TIME FROM 3 FOR 2) 
			END AS Investigation6RequestTime,

			T1.THECODE AS Treatment1TreatmentType,
			T1.REQUEST_DATE AS Treatment1TreatmentDate,
			CASE
				WHEN T1.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(T1.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN T1.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(T1.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(T1.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(T1.REQUEST_TIME FROM 3 FOR 2) 
			END AS Treatment1TreatmentTime,
			T2.THECODE AS Treatment2TreatmentType,
			T2.REQUEST_DATE AS Treatment2TreatmentDate,
			CASE
				WHEN T2.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(T2.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN T2.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(T2.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(T2.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(T2.REQUEST_TIME FROM 3 FOR 2) 
			END AS Treatment2TreatmentTime,
			T3.THECODE AS Treatment3TreatmentType,
			T3.REQUEST_DATE AS Treatment3TreatmentDate,
			CASE
				WHEN T3.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(T3.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN T3.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(T3.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(T3.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(T3.REQUEST_TIME FROM 3 FOR 2) 
			END AS Treatment3TreatmentTime,
			T4.THECODE AS Treatment4TreatmentType,
			T4.REQUEST_DATE AS Treatment4TreatmentDate,
			CASE
				WHEN T4.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(T4.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN T4.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(T4.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(T4.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(T4.REQUEST_TIME FROM 3 FOR 2) 
			END AS Treatment4TreatmentTime,
			T5.THECODE AS Treatment5TreatmentType,
			T5.REQUEST_DATE AS Treatment5TreatmentDate,
			CASE
				WHEN T5.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(T5.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN T5.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(T5.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(T5.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(T5.REQUEST_TIME FROM 3 FOR 2) 
			END AS Treatment5TreatmentTime,
			T6.THECODE AS Treatment6TreatmentType,
			T6.REQUEST_DATE AS Treatment6TreatmentDate,
			CASE
				WHEN T6.REQUEST_TIME IS NULL THEN NULL
				WHEN TRIM(T6.REQUEST_TIME)='':'' THEN ''00:00''
				WHEN T6.REQUEST_TIME IS NULL THEN ''00:00''
				WHEN TRIM(T6.REQUEST_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(T6.REQUEST_TIME FROM 1 FOR 2)||'':''||SUBSTRING(T6.REQUEST_TIME FROM 3 FOR 2) 
			END AS Treatment6TreatmentTime,
			CASE
				WHEN ED.PATIENT_WHAT_DOING=''CS'' THEN ''6''
				WHEN ED.PATIENT_WHAT_DOING=''NO'' THEN ''27''
				ELSE ''98''
			END AS SportsActivity,
			CASE 
				WHEN ED.PATIENT_DISPOSAL=''DNW'' THEN ''Y'' 
				ELSE NULL 
			END AS LeftWithoutSeen,
			T.GPREFNO AS CascardNumber,
			NULL AS PatientRefNo,
			BH1.BREACH_KEY AS BREACHKEY1,
			BH1.BREACH_REASON AS BREACHREASON1,
			CAST(BH1.BREACH_START AS DATE) AS BREACHSTARTDATE1,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH1.BREACH_START) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH1.BREACH_START) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH1.BREACH_START) AS BREACHSTARTTIME1,
			CAST(BH1.BREACH_END AS DATE) AS BREACHENDDATE1,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH1.BREACH_END) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH1.BREACH_END) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH1.BREACH_END) AS BREACHENDTIME1,
			BH2.BREACH_KEY AS BREACHKEY2,
			BH2.BREACH_REASON AS BREACHREASON2,
			CAST(BH2.BREACH_START AS DATE) AS BREACHSTARTDATE2,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH2.BREACH_START) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH2.BREACH_START) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH2.BREACH_START) AS BREACHSTARTTIME2,
			CAST(BH2.BREACH_END AS DATE) AS BREACHENDDATE2,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH2.BREACH_END) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH2.BREACH_END) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH2.BREACH_END) AS BREACHENDTIME2,
			BH3.BREACH_KEY AS BREACHKEY3,
			BH3.BREACH_REASON AS BREACHREASON3,
			CAST(BH3.BREACH_START AS DATE) AS BREACHSTARTDATE3,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH3.BREACH_START) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH3.BREACH_START) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH3.BREACH_START) AS BREACHSTARTTIME3,
			CAST(BH3.BREACH_END AS DATE) AS BREACHENDDATE3,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH3.BREACH_END) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH3.BREACH_END) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH3.BREACH_END) AS BREACHENDTIME3,
			BH4.BREACH_KEY AS BREACHKEY4,
			BH4.BREACH_REASON AS BREACHREASON4,
			CAST(BH4.BREACH_START AS DATE) AS BREACHSTARTDATE4,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH4.BREACH_START) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH4.BREACH_START) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH4.BREACH_START) AS BREACHSTARTTIME4,
			CAST(BH4.BREACH_END AS DATE) AS BREACHENDDATE4,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH4.BREACH_END) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH4.BREACH_END) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH4.BREACH_END) AS BREACHENDTIME4,
			BH5.BREACH_KEY AS BREACHKEY5,
			BH5.BREACH_REASON AS BREACHREASON5,
			CAST(BH5.BREACH_START AS DATE) AS BREACHSTARTDATE5,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH5.BREACH_START) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH5.BREACH_START) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH5.BREACH_START) AS BREACHSTARTTIME5,
			CAST(BH5.BREACH_END AS DATE) AS BREACHENDDATE5,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH5.BREACH_END) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH5.BREACH_END) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH5.BREACH_END) AS BREACHENDTIME5,
			BH6.BREACH_KEY AS BREACHKEY6,
			BH6.BREACH_REASON AS BREACHREASON6,
			CAST(BH6.BREACH_START AS DATE) AS BREACHSTARTDATE6,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH6.BREACH_START) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH6.BREACH_START) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH6.BREACH_START) AS BREACHSTARTTIME,
			CAST(BH6.BREACH_END AS DATE) AS BREACHENDDATE6,
			RIGHT(''0''||CAST(EXTRACT(HOUR FROM BH6.BREACH_END) AS VARCHAR(2)),2)||'':''||RIGHT(''0''||CAST(EXTRACT(MINUTE FROM BH6.BREACH_END) AS VARCHAR(2)),2)||'':''||EXTRACT(SECOND FROM BH6.BREACH_END) AS BREACHENDTIME6,
			
			CAST(CR1.REQUEST_DATE AS DATE) AS ConsultationRequestDate1,
			LEFT(CR1.REQUEST_TIME,2)||'':''||RIGHT(CR1.REQUEST_TIME,2) AS ConsultationRequestTime1,
			CAST(CR1.REQUEST_COMPLETED AS DATE) AS ConsultationRequestCompletedDate1,
			LEFT(CR1.REQUEST_COMPLETEDTIME,2)||'':''||RIGHT(CR1.REQUEST_COMPLETEDTIME,2) AS ConsultationRequestCompletedTime1,
			CR1.REQUEST_SPECIALTY AS ConsultationRequestSpecialty1,
			
			CAST(CR2.REQUEST_DATE AS DATE) AS ConsultationRequestDate2,
			LEFT(CR2.REQUEST_TIME,2)||'':''||RIGHT(CR2.REQUEST_TIME,2) AS ConsultationRequestTime2,
			CAST(CR2.REQUEST_COMPLETED AS DATE) AS ConsultationRequestCompletedDate2,
			LEFT(CR2.REQUEST_COMPLETEDTIME,2)||'':''||RIGHT(CR2.REQUEST_COMPLETEDTIME,2) AS ConsultationRequestCompletedTime2,
			CR2.REQUEST_SPECIALTY AS ConsultationRequestSpecialty2,
			
			CAST(CR3.REQUEST_DATE AS DATE) AS ConsultationRequestDate3,
			LEFT(CR3.REQUEST_TIME,2)||'':''||RIGHT(CR3.REQUEST_TIME,2) AS ConsultationRequestTime3,
			CAST(CR3.REQUEST_COMPLETED AS DATE) AS ConsultationRequestCompletedDate3,
			LEFT(CR3.REQUEST_COMPLETEDTIME,2)||'':''||RIGHT(CR3.REQUEST_COMPLETEDTIME,2) AS ConsultationRequestCompletedTime3,
			CR3.REQUEST_SPECIALTY AS ConsultationRequestSpecialty3,
			
			CAST(CR4.REQUEST_DATE AS DATE) AS ConsultationRequestDate4,
			LEFT(CR4.REQUEST_TIME,2)||'':''||RIGHT(CR4.REQUEST_TIME,2) AS ConsultationRequestTime4,
			CAST(CR4.REQUEST_COMPLETED AS DATE) AS ConsultationRequestCompletedDate4,
			LEFT(CR4.REQUEST_COMPLETEDTIME,2)||'':''||RIGHT(CR4.REQUEST_COMPLETEDTIME,2) AS ConsultationRequestCompletedTime4,
			CR4.REQUEST_SPECIALTY AS ConsultationRequestSpecialty4,
			
			CAST(CR5.REQUEST_DATE AS DATE) AS ConsultationRequestDate5,
			LEFT(CR5.REQUEST_TIME,2)||'':''||RIGHT(CR5.REQUEST_TIME,2) AS ConsultationRequestTime5,
			CAST(CR5.REQUEST_COMPLETED AS DATE) AS ConsultationRequestCompletedDate5,
			LEFT(CR5.REQUEST_COMPLETEDTIME,2)||'':''||RIGHT(CR5.REQUEST_COMPLETEDTIME,2) AS ConsultationRequestCompletedTime5,
			CR5.REQUEST_SPECIALTY AS ConsultationRequestSpecialty5,
			
			CAST(CR6.REQUEST_DATE AS DATE) AS ConsultationRequestDate6,
			LEFT(CR6.REQUEST_TIME,2)||'':''||RIGHT(CR6.REQUEST_TIME,2) AS ConsultationRequestTime6,
			CAST(CR6.REQUEST_COMPLETED AS DATE) AS ConsultationRequestCompletedDate6,
			LEFT(CR6.REQUEST_COMPLETEDTIME,2)||'':''||RIGHT(CR6.REQUEST_COMPLETEDTIME,2) AS ConsultationRequestCompletedTime6,
			CR6.REQUEST_SPECIALTY AS ConsultationRequestSpecialty6,
			NULL AS AttendanceNumber
		FROM 
			TREATMNT T
			LEFT JOIN AANDE_DATA ED ON T.LINKID=ED.LINKID
			LEFT JOIN TRIAGEDI TD ON ED.DISCRIMINATOR_ID=TD.DISCRIMINATOR_ID
			LEFT JOIN PATIENT P ON T.CASENO = P.CASENO
			--LEFT JOIN AANDE_BREACH_HISTORY BH ON T.LINKID=BH.LINKID 
			--	AND BH.BREACH_KEY=(SELECT FIRST 1(innerBH.BREACH_KEY) FROM AANDE_BREACH_HISTORY innerBH WHERE innerBH.LINKID=T.LINKID AND innerBH.BREACH_END IS NOT NULL ORDER BY innerBH.BREACH_END ASC) 
			
			LEFT JOIN REFER R ON T.LINKID=R.LINKID
			LEFT JOIN PADLOC ON T.ALOC=PADLOC.LOCCODE
			--LEFT JOIN GP2 EDCS ON ED.TREATMENT_BY = EDCS.PRACTICE AND EDCS.RECORD_TYPE=''C''
			LEFT JOIN AANDE_CODING D1 ON T.LINKID=D1.LINKID AND D1.CODE_TYPE=''ED'' AND D1.SEQ_NO=(SELECT FIRST 1 innerD1.SEQ_NO FROM AANDE_CODING innerD1 WHERE innerD1.LINKID=T.LINKID AND innerD1.CODE_TYPE=''ED'' ORDER BY innerD1.ITEMNO ASC, innerD1.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING D2 ON T.LINKID=D2.LINKID AND D2.CODE_TYPE=''ED'' AND D2.SEQ_NO=(SELECT FIRST 1 SKIP 1 innerD2.SEQ_NO FROM AANDE_CODING innerD2 WHERE innerD2.LINKID=T.LINKID AND innerD2.CODE_TYPE=''ED'' ORDER BY innerD2.ITEMNO ASC, innerD2.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING D3 ON T.LINKID=D3.LINKID AND D3.CODE_TYPE=''ED'' AND D3.SEQ_NO=(SELECT FIRST 1 SKIP 2 innerD3.SEQ_NO FROM AANDE_CODING innerD3 WHERE innerD3.LINKID=T.LINKID AND innerD3.CODE_TYPE=''ED'' ORDER BY innerD3.ITEMNO ASC, innerD3.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING D4 ON T.LINKID=D4.LINKID AND D4.CODE_TYPE=''ED'' AND D4.SEQ_NO=(SELECT FIRST 1 SKIP 3 innerD4.SEQ_NO FROM AANDE_CODING innerD4 WHERE innerD4.LINKID=T.LINKID AND innerD4.CODE_TYPE=''ED'' ORDER BY innerD4.ITEMNO ASC, innerD4.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING D5 ON T.LINKID=D5.LINKID AND D5.CODE_TYPE=''ED'' AND D5.SEQ_NO=(SELECT FIRST 1 SKIP 4 innerD5.SEQ_NO FROM AANDE_CODING innerD5 WHERE innerD5.LINKID=T.LINKID AND innerD5.CODE_TYPE=''ED'' ORDER BY innerD5.ITEMNO ASC, innerD5.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING D6 ON T.LINKID=D6.LINKID AND D6.CODE_TYPE=''ED'' AND D6.SEQ_NO=(SELECT FIRST 1 SKIP 5 innerD6.SEQ_NO FROM AANDE_CODING innerD6 WHERE innerD6.LINKID=T.LINKID AND innerD6.CODE_TYPE=''ED'' ORDER BY innerD6.ITEMNO ASC, innerD6.SEQ_NO DESC)
			--LEFT JOIN AANDE_CODING D1 ON ED.LINKID=D1.LINKID AND D1.CODE_TYPE=''ED'' AND D1.ITEMNO=1 --Repeated ItemNos - lots of them
			--LEFT JOIN AANDE_CODING D2 ON ED.LINKID=D2.LINKID AND D2.CODE_TYPE=''ED'' AND D2.ITEMNO=2
			--LEFT JOIN AANDE_CODING D3 ON ED.LINKID=D3.LINKID AND D3.CODE_TYPE=''ED'' AND D3.ITEMNO=3
			--LEFT JOIN AANDE_CODING D4 ON ED.LINKID=D4.LINKID AND D4.CODE_TYPE=''ED'' AND D4.ITEMNO=4
			--LEFT JOIN AANDE_CODING D5 ON ED.LINKID=D5.LINKID AND D5.CODE_TYPE=''ED'' AND D5.ITEMNO=5
			--LEFT JOIN AANDE_CODING D6 ON ED.LINKID=D6.LINKID AND D6.CODE_TYPE=''ED'' AND D6.ITEMNO=6
			--LEFT JOIN AANDE_CODING DST1 ON ED.LINKID=DST1.LINKID AND DST1.CODE_TYPE=''ED'' AND DST1.REQUEST_SITETYPE=''ST'' AND DST1.ITEMNO=1
			--LEFT JOIN AANDE_CODING DST2 ON ED.LINKID=DST2.LINKID AND DST2.CODE_TYPE=''ED'' AND DST2.REQUEST_SITETYPE=''ST'' AND DST2.ITEMNO=2
			--LEFT JOIN AANDE_CODING DST3 ON ED.LINKID=DST3.LINKID AND DST3.CODE_TYPE=''ED'' AND DST3.REQUEST_SITETYPE=''ST'' AND DST3.ITEMNO=3
			--LEFT JOIN AANDE_CODING DST4 ON ED.LINKID=DST4.LINKID AND DST4.CODE_TYPE=''ED'' AND DST4.REQUEST_SITETYPE=''ST'' AND DST4.ITEMNO=4
			--LEFT JOIN AANDE_CODING DST5 ON ED.LINKID=DST5.LINKID AND DST5.CODE_TYPE=''ED'' AND DST5.REQUEST_SITETYPE=''ST'' AND DST5.ITEMNO=5
			--LEFT JOIN AANDE_CODING DST6 ON ED.LINKID=DST6.LINKID AND DST6.CODE_TYPE=''ED'' AND DST6.REQUEST_SITETYPE=''ST'' AND DST6.ITEMNO=6
			--LEFT JOIN AANDE_CODING DSI1 ON ED.LINKID=DSI1.LINKID AND DSI1.CODE_TYPE=''ED'' AND DSI1.REQUEST_SIDETYPE=''SI'' AND DSI1.ITEMNO=1
			--LEFT JOIN AANDE_CODING DSI2 ON ED.LINKID=DSI2.LINKID AND DSI2.CODE_TYPE=''ED'' AND DSI2.REQUEST_SIDETYPE=''SI'' AND DSI2.ITEMNO=2
			--LEFT JOIN AANDE_CODING DSI3 ON ED.LINKID=DSI3.LINKID AND DSI3.CODE_TYPE=''ED'' AND DSI3.REQUEST_SIDETYPE=''SI'' AND DSI3.ITEMNO=3
			--LEFT JOIN AANDE_CODING DSI4 ON ED.LINKID=DSI4.LINKID AND DSI4.CODE_TYPE=''ED'' AND DSI4.REQUEST_SIDETYPE=''SI'' AND DSI4.ITEMNO=4
			--LEFT JOIN AANDE_CODING DSI5 ON ED.LINKID=DSI5.LINKID AND DSI5.CODE_TYPE=''ED'' AND DSI5.REQUEST_SIDETYPE=''SI'' AND DSI5.ITEMNO=5
			--LEFT JOIN AANDE_CODING DSI6 ON ED.LINKID=DSI6.LINKID AND DSI6.CODE_TYPE=''ED'' AND DSI6.REQUEST_SIDETYPE=''SI'' AND DSI6.ITEMNO=6
			
			LEFT JOIN AANDE_CODING X1 ON T.LINKID=X1.LINKID AND X1.CODE_TYPE=''RT'' AND X1.SEQ_NO=(SELECT FIRST 1 innerX1.SEQ_NO FROM AANDE_CODING innerX1 WHERE innerX1.LINKID=T.LINKID AND innerX1.CODE_TYPE=''RT'' ORDER BY innerX1.ITEMNO ASC, innerX1.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING X2 ON T.LINKID=X2.LINKID AND X2.CODE_TYPE=''RT'' AND X2.SEQ_NO=(SELECT FIRST 1 SKIP 1 innerX2.SEQ_NO FROM AANDE_CODING innerX2 WHERE innerX2.LINKID=T.LINKID AND innerX2.CODE_TYPE=''RT'' ORDER BY innerX2.ITEMNO ASC, innerX2.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING X3 ON T.LINKID=X3.LINKID AND X3.CODE_TYPE=''RT'' AND X3.SEQ_NO=(SELECT FIRST 1 SKIP 2 innerX3.SEQ_NO FROM AANDE_CODING innerX3 WHERE innerX3.LINKID=T.LINKID AND innerX3.CODE_TYPE=''RT'' ORDER BY innerX3.ITEMNO ASC, innerX3.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING X4 ON T.LINKID=X4.LINKID AND X4.CODE_TYPE=''RT'' AND X4.SEQ_NO=(SELECT FIRST 1 SKIP 3 innerX4.SEQ_NO FROM AANDE_CODING innerX4 WHERE innerX4.LINKID=T.LINKID AND innerX4.CODE_TYPE=''RT'' ORDER BY innerX4.ITEMNO ASC, innerX4.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING X5 ON T.LINKID=X5.LINKID AND X5.CODE_TYPE=''RT'' AND X5.SEQ_NO=(SELECT FIRST 1 SKIP 4 innerX5.SEQ_NO FROM AANDE_CODING innerX5 WHERE innerX5.LINKID=T.LINKID AND innerX5.CODE_TYPE=''RT'' ORDER BY innerX5.ITEMNO ASC, innerX5.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING X6 ON T.LINKID=X6.LINKID AND X6.CODE_TYPE=''RT'' AND X6.SEQ_NO=(SELECT FIRST 1 SKIP 5 innerX6.SEQ_NO FROM AANDE_CODING innerX6 WHERE innerX6.LINKID=T.LINKID AND innerX6.CODE_TYPE=''RT'' ORDER BY innerX6.ITEMNO ASC, innerX6.SEQ_NO DESC)
			--LEFT JOIN AANDE_CODING X1 ON ED.LINKID=X1.LINKID AND X1.CODE_TYPE=''RT'' AND X1.ITEMNO=1 --Currently no repeated ItemNos but changing it anyway
			--LEFT JOIN AANDE_CODING X2 ON ED.LINKID=X2.LINKID AND X2.CODE_TYPE=''RT'' AND X2.ITEMNO=2
			--LEFT JOIN AANDE_CODING X3 ON ED.LINKID=X3.LINKID AND X3.CODE_TYPE=''RT'' AND X3.ITEMNO=3
			--LEFT JOIN AANDE_CODING X4 ON ED.LINKID=X4.LINKID AND X4.CODE_TYPE=''RT'' AND X4.ITEMNO=4
			--LEFT JOIN AANDE_CODING X5 ON ED.LINKID=X5.LINKID AND X5.CODE_TYPE=''RT'' AND X5.ITEMNO=5
			--LEFT JOIN AANDE_CODING X6 ON ED.LINKID=X6.LINKID AND X6.CODE_TYPE=''RT'' AND X6.ITEMNO=6
			--LEFT JOIN AANDE_CODING XST1 ON ED.LINKID=XST1.LINKID AND XST1.CODE_TYPE=''RT'' AND XST1.REQUEST_SITETYPE=''RL'' AND XST1.ITEMNO=1 --Using the X1 etc tables
			--LEFT JOIN AANDE_CODING XST2 ON ED.LINKID=XST2.LINKID AND XST2.CODE_TYPE=''RT'' AND XST2.REQUEST_SITETYPE=''RL'' AND XST2.ITEMNO=2
			--LEFT JOIN AANDE_CODING XST3 ON ED.LINKID=XST3.LINKID AND XST3.CODE_TYPE=''RT'' AND XST3.REQUEST_SITETYPE=''RL'' AND XST3.ITEMNO=3
			--LEFT JOIN AANDE_CODING XST4 ON ED.LINKID=XST4.LINKID AND XST4.CODE_TYPE=''RT'' AND XST4.REQUEST_SITETYPE=''RL'' AND XST4.ITEMNO=4
			--LEFT JOIN AANDE_CODING XST5 ON ED.LINKID=XST5.LINKID AND XST5.CODE_TYPE=''RT'' AND XST5.REQUEST_SITETYPE=''RL'' AND XST5.ITEMNO=5
			--LEFT JOIN AANDE_CODING XST6 ON ED.LINKID=XST6.LINKID AND XST6.CODE_TYPE=''RT'' AND XST6.REQUEST_SITETYPE=''RL'' AND XST6.ITEMNO=6
			--LEFT JOIN AANDE_CODING XSD1 ON ED.LINKID=XSD1.LINKID AND XSD1.CODE_TYPE=''RT'' AND XSD1.REQUEST_SIDETYPE=''RS'' AND XSD1.ITEMNO=1
			--LEFT JOIN AANDE_CODING XSD2 ON ED.LINKID=XSD2.LINKID AND XSD2.CODE_TYPE=''RT'' AND XSD2.REQUEST_SIDETYPE=''RS'' AND XSD2.ITEMNO=2
			--LEFT JOIN AANDE_CODING XSD3 ON ED.LINKID=XSD3.LINKID AND XSD3.CODE_TYPE=''RT'' AND XSD3.REQUEST_SIDETYPE=''RS'' AND XSD3.ITEMNO=3
			--LEFT JOIN AANDE_CODING XSD4 ON ED.LINKID=XSD4.LINKID AND XSD4.CODE_TYPE=''RT'' AND XSD4.REQUEST_SIDETYPE=''RS'' AND XSD4.ITEMNO=4
			--LEFT JOIN AANDE_CODING XSD5 ON ED.LINKID=XSD5.LINKID AND XSD5.CODE_TYPE=''RT'' AND XSD5.REQUEST_SIDETYPE=''RS'' AND XSD5.ITEMNO=5
			--LEFT JOIN AANDE_CODING XSD6 ON ED.LINKID=XSD6.LINKID AND XSD6.CODE_TYPE=''RT'' AND XSD6.REQUEST_SIDETYPE=''RS'' AND XSD6.ITEMNO=6

			LEFT JOIN AANDE_CODING I1 ON T.LINKID=I1.LINKID AND I1.CODE_TYPE=''EI'' AND I1.SEQ_NO=(SELECT FIRST 1 innerI1.SEQ_NO FROM AANDE_CODING innerI1 WHERE innerI1.LINKID=T.LINKID AND innerI1.CODE_TYPE=''EI'' ORDER BY innerI1.ITEMNO ASC, innerI1.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING I2 ON T.LINKID=I2.LINKID AND I2.CODE_TYPE=''EI'' AND I2.SEQ_NO=(SELECT FIRST 1 SKIP 1 innerI2.SEQ_NO FROM AANDE_CODING innerI2 WHERE innerI2.LINKID=T.LINKID AND innerI2.CODE_TYPE=''EI'' ORDER BY innerI2.ITEMNO ASC, innerI2.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING I3 ON T.LINKID=I3.LINKID AND I3.CODE_TYPE=''EI'' AND I3.SEQ_NO=(SELECT FIRST 1 SKIP 2 innerI3.SEQ_NO FROM AANDE_CODING innerI3 WHERE innerI3.LINKID=T.LINKID AND innerI3.CODE_TYPE=''EI'' ORDER BY innerI3.ITEMNO ASC, innerI3.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING I4 ON T.LINKID=I4.LINKID AND I4.CODE_TYPE=''EI'' AND I4.SEQ_NO=(SELECT FIRST 1 SKIP 3 innerI4.SEQ_NO FROM AANDE_CODING innerI4 WHERE innerI4.LINKID=T.LINKID AND innerI4.CODE_TYPE=''EI'' ORDER BY innerI4.ITEMNO ASC, innerI4.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING I5 ON T.LINKID=I5.LINKID AND I5.CODE_TYPE=''EI'' AND I5.SEQ_NO=(SELECT FIRST 1 SKIP 4 innerI5.SEQ_NO FROM AANDE_CODING innerI5 WHERE innerI5.LINKID=T.LINKID AND innerI5.CODE_TYPE=''EI'' ORDER BY innerI5.ITEMNO ASC, innerI5.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING I6 ON T.LINKID=I6.LINKID AND I6.CODE_TYPE=''EI'' AND I6.SEQ_NO=(SELECT FIRST 1 SKIP 5 innerI6.SEQ_NO FROM AANDE_CODING innerI6 WHERE innerI6.LINKID=T.LINKID AND innerI6.CODE_TYPE=''EI'' ORDER BY innerI6.ITEMNO ASC, innerI6.SEQ_NO DESC)
			--LEFT JOIN AANDE_CODING I1 ON ED.LINKID=I1.LINKID AND I1.CODE_TYPE=''EI'' AND I1.ITEMNO=1 --Repeated ItemNos LinkId M10460393
			--LEFT JOIN AANDE_CODING I2 ON ED.LINKID=I2.LINKID AND I2.CODE_TYPE=''EI'' AND I2.ITEMNO=2
			--LEFT JOIN AANDE_CODING I3 ON ED.LINKID=I3.LINKID AND I3.CODE_TYPE=''EI'' AND I3.ITEMNO=3
			--LEFT JOIN AANDE_CODING I4 ON ED.LINKID=I4.LINKID AND I4.CODE_TYPE=''EI'' AND I4.ITEMNO=4
			--LEFT JOIN AANDE_CODING I5 ON ED.LINKID=I5.LINKID AND I5.CODE_TYPE=''EI'' AND I5.ITEMNO=5
			--LEFT JOIN AANDE_CODING I6 ON ED.LINKID=I6.LINKID AND I6.CODE_TYPE=''EI'' AND I6.ITEMNO=6
			

			LEFT JOIN AANDE_CODING T1 ON T.LINKID=T1.LINKID AND T1.CODE_TYPE=''EA'' AND T1.SEQ_NO=(SELECT FIRST 1 innerT1.SEQ_NO FROM AANDE_CODING innerT1 WHERE innerT1.LINKID=T.LINKID AND innerT1.CODE_TYPE=''EA'' ORDER BY innerT1.ITEMNO ASC, innerT1.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING T2 ON T.LINKID=T2.LINKID AND T2.CODE_TYPE=''EA'' AND T2.SEQ_NO=(SELECT FIRST 1 SKIP 1 innerT2.SEQ_NO FROM AANDE_CODING innerT2 WHERE innerT2.LINKID=T.LINKID AND innerT2.CODE_TYPE=''EA'' ORDER BY innerT2.ITEMNO ASC, innerT2.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING T3 ON T.LINKID=T3.LINKID AND T3.CODE_TYPE=''EA'' AND T3.SEQ_NO=(SELECT FIRST 1 SKIP 2 innerT3.SEQ_NO FROM AANDE_CODING innerT3 WHERE innerT3.LINKID=T.LINKID AND innerT3.CODE_TYPE=''EA'' ORDER BY innerT3.ITEMNO ASC, innerT3.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING T4 ON T.LINKID=T4.LINKID AND T4.CODE_TYPE=''EA'' AND T4.SEQ_NO=(SELECT FIRST 1 SKIP 3 innerT4.SEQ_NO FROM AANDE_CODING innerT4 WHERE innerT4.LINKID=T.LINKID AND innerT4.CODE_TYPE=''EA'' ORDER BY innerT4.ITEMNO ASC, innerT4.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING T5 ON T.LINKID=T5.LINKID AND T5.CODE_TYPE=''EA'' AND T5.SEQ_NO=(SELECT FIRST 1 SKIP 4 innerT5.SEQ_NO FROM AANDE_CODING innerT5 WHERE innerT5.LINKID=T.LINKID AND innerT5.CODE_TYPE=''EA'' ORDER BY innerT5.ITEMNO ASC, innerT5.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING T6 ON T.LINKID=T6.LINKID AND T6.CODE_TYPE=''EA'' AND T6.SEQ_NO=(SELECT FIRST 1 SKIP 5 innerT6.SEQ_NO FROM AANDE_CODING innerT6 WHERE innerT6.LINKID=T.LINKID AND innerT6.CODE_TYPE=''EA'' ORDER BY innerT6.ITEMNO ASC, innerT6.SEQ_NO DESC)
			--LEFT JOIN AANDE_CODING T1 ON ED.LINKID=T1.LINKID AND T1.CODE_TYPE=''EA'' AND T1.ITEMNO=1 --Repeated ItemNos
			--LEFT JOIN AANDE_CODING T2 ON ED.LINKID=T2.LINKID AND T2.CODE_TYPE=''EA'' AND T2.ITEMNO=2
			--LEFT JOIN AANDE_CODING T3 ON ED.LINKID=T3.LINKID AND T3.CODE_TYPE=''EA'' AND T3.ITEMNO=3
			--LEFT JOIN AANDE_CODING T4 ON ED.LINKID=T4.LINKID AND T4.CODE_TYPE=''EA'' AND T4.ITEMNO=4
			--LEFT JOIN AANDE_CODING T5 ON ED.LINKID=T5.LINKID AND T5.CODE_TYPE=''EA'' AND T5.ITEMNO=5
			--LEFT JOIN AANDE_CODING T6 ON ED.LINKID=T6.LINKID AND T6.CODE_TYPE=''EA'' AND T6.ITEMNO=6
			
			LEFT JOIN AANDE_BREACH_HISTORY BH1 ON T.LINKID=BH1.LINKID AND BH1.BREACH_KEY=(SELECT FIRST 1 innerBH1.BREACH_KEY FROM AANDE_BREACH_HISTORY innerBH1 WHERE innerBH1.LINKID=T.LINKID ORDER BY innerBH1.BREACH_START,innerBH1.BREACH_KEY)
			LEFT JOIN AANDE_BREACH_HISTORY BH2 ON T.LINKID=BH2.LINKID AND BH2.BREACH_KEY=(SELECT FIRST 1 SKIP 1 innerBH2.BREACH_KEY FROM AANDE_BREACH_HISTORY innerBH2 WHERE innerBH2.LINKID=T.LINKID ORDER BY innerBH2.BREACH_START,innerBH2.BREACH_KEY)
			LEFT JOIN AANDE_BREACH_HISTORY BH3 ON T.LINKID=BH3.LINKID AND BH3.BREACH_KEY=(SELECT FIRST 1 SKIP 2 innerBH3.BREACH_KEY FROM AANDE_BREACH_HISTORY innerBH3 WHERE innerBH3.LINKID=T.LINKID ORDER BY innerBH3.BREACH_START,innerBH3.BREACH_KEY)
			LEFT JOIN AANDE_BREACH_HISTORY BH4 ON T.LINKID=BH4.LINKID AND BH4.BREACH_KEY=(SELECT FIRST 1 SKIP 3 innerBH4.BREACH_KEY FROM AANDE_BREACH_HISTORY innerBH4 WHERE innerBH4.LINKID=T.LINKID ORDER BY innerBH4.BREACH_START,innerBH4.BREACH_KEY)
			LEFT JOIN AANDE_BREACH_HISTORY BH5 ON T.LINKID=BH5.LINKID AND BH5.BREACH_KEY=(SELECT FIRST 1 SKIP 4 innerBH5.BREACH_KEY FROM AANDE_BREACH_HISTORY innerBH5 WHERE innerBH5.LINKID=T.LINKID ORDER BY innerBH5.BREACH_START,innerBH5.BREACH_KEY)
			LEFT JOIN AANDE_BREACH_HISTORY BH6 ON T.LINKID=BH6.LINKID AND BH6.BREACH_KEY=(SELECT FIRST 1 SKIP 5 innerBH6.BREACH_KEY FROM AANDE_BREACH_HISTORY innerBH6 WHERE innerBH6.LINKID=T.LINKID ORDER BY innerBH6.BREACH_START,innerBH6.BREACH_KEY)
			
			LEFT JOIN AANDE_CODING CR1 ON T.LINKID=CR1.LINKID AND CR1.THECODE=''CON'' AND CR1.SEQ_NO=(SELECT FIRST 1 innerCR1.SEQ_NO FROM AANDE_CODING innerCR1 WHERE innerCR1.LINKID=T.LINKID AND innerCR1.THECODE=''CON'' ORDER BY innerCR1.ITEMNO, innerCR1.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING CR2 ON T.LINKID=CR2.LINKID AND CR2.THECODE=''CON'' AND CR2.SEQ_NO=(SELECT FIRST 1 SKIP 1 innerCR2.SEQ_NO FROM AANDE_CODING innerCR2 WHERE innerCR2.LINKID=T.LINKID AND innerCR2.THECODE=''CON'' ORDER BY innerCR2.ITEMNO ASC, innerCR2.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING CR3 ON T.LINKID=CR3.LINKID AND CR3.THECODE=''CON'' AND CR3.SEQ_NO=(SELECT FIRST 1 SKIP 2 innerCR3.SEQ_NO FROM AANDE_CODING innerCR3 WHERE innerCR3.LINKID=T.LINKID AND innerCR3.THECODE=''CON'' ORDER BY innerCR3.ITEMNO ASC, innerCR3.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING CR4 ON T.LINKID=CR4.LINKID AND CR4.THECODE=''CON'' AND CR4.SEQ_NO=(SELECT FIRST 1 SKIP 3 innerCR4.SEQ_NO FROM AANDE_CODING innerCR4 WHERE innerCR4.LINKID=T.LINKID AND innerCR4.THECODE=''CON'' ORDER BY innerCR4.ITEMNO ASC, innerCR4.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING CR5 ON T.LINKID=CR5.LINKID AND CR5.THECODE=''CON'' AND CR5.SEQ_NO=(SELECT FIRST 1 SKIP 4 innerCR5.SEQ_NO FROM AANDE_CODING innerCR5 WHERE innerCR5.LINKID=T.LINKID AND innerCR5.THECODE=''CON'' ORDER BY innerCR5.ITEMNO ASC, innerCR5.SEQ_NO DESC)
			LEFT JOIN AANDE_CODING CR6 ON T.LINKID=CR6.LINKID AND CR6.THECODE=''CON'' AND CR6.SEQ_NO=(SELECT FIRST 1 SKIP 5 innerCR6.SEQ_NO FROM AANDE_CODING innerCR6 WHERE innerCR6.LINKID=T.LINKID AND innerCR6.THECODE=''CON'' ORDER BY innerCR6.ITEMNO ASC, innerCR6.SEQ_NO DESC)
			--LEFT JOIN AANDE_CLOSEREQUEST CR1 ON ED.LINKID=CR1.LINKID AND CR1.THECODE=''CON'' AND CR1.ITEMNO=1 --Repeated ItemNos
			--LEFT JOIN AANDE_CLOSEREQUEST CR2 ON ED.LINKID=CR2.LINKID AND CR2.THECODE=''CON'' AND CR2.ITEMNO=2
			--LEFT JOIN AANDE_CLOSEREQUEST CR3 ON ED.LINKID=CR3.LINKID AND CR3.THECODE=''CON'' AND CR3.ITEMNO=3
			--LEFT JOIN AANDE_CLOSEREQUEST CR4 ON ED.LINKID=CR4.LINKID AND CR4.THECODE=''CON'' AND CR4.ITEMNO=4
			--LEFT JOIN AANDE_CLOSEREQUEST CR5 ON ED.LINKID=CR5.LINKID AND CR5.THECODE=''CON'' AND CR5.ITEMNO=5
			--LEFT JOIN AANDE_CLOSEREQUEST CR6 ON ED.LINKID=CR6.LINKID AND CR6.THECODE=''CON'' AND CR6.ITEMNO=6
		WHERE
			T.TRT_TYPE IN (''EC'',''ED'') AND
			LEFT(ED.LINKID,2)!=''XE'' AND 
			ED.ARRIVAL_DATE > '''+@LastAttendanceDateString+''' AND 
			ED.ARRIVAL_DATE < '''+@DateToString+'''
	'
	) AT [WPAS_Central_Newport];


END

GO
