SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[Get_PAS_Data_WardTransferEast]
	
AS
BEGIN
	
	SET NOCOUNT ON;

	
DECLARE @StartDate AS DATE = CAST((SELECT ISNULL(MAX(EventStartDate),'1 JANUARY 2015') FROM [Foundation].[dbo].[PAS_Data_WardTransfer] WHERE Type='A' AND Area='East') AS DATE)
DECLARE @EndDate AS VARCHAR(30) = DATENAME(DAY,GETDATE()) + ' ' + DATENAME(MONTH,GETDATE()) + ' ' + DATENAME(YEAR,GETDATE())

--DECLARE @StartDate AS DATE = '1 APRIL 2015'
--DECLARE @EndDate AS DATE = CAST(GETDATE() AS DATE)--'30 APRIL 2018'

EXEC('
	SELECT * FROM(
		SELECT 
			''East'' AS Area,
			''Myrddin'' AS Source,
			TREAT.CASENO AS LocalPatientIdentifier,
			TRANS.LINKID AS SpellNumber,
			TRANS.TRANSFER_NO AS TransferNumber,
			TRANS.EPISODENO AS EpisodeNumber,
			CAST(TRANS.TRANSFER_DATE AS DATE) AS EventStartDate,
			CASE
				WHEN TRANS.TRANSFER_DATE IS NULL THEN NULL
				WHEN TRIM(TRANS.TRANSFER_TIME)='':'' THEN ''00:00''
				WHEN TRANS.TRANSFER_TIME IS NULL THEN ''00:00''
				WHEN TRIM(TRANS.TRANSFER_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(TRANS.TRANSFER_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TRANS.TRANSFER_TIME FROM 3 FOR 2) 
			END AS EventStartTime,
			CAST(CASE
				WHEN TRANS.TRANSFER_NO = (SELECT MAX(TRANSFER_NO) FROM TRANSFER innerT WHERE innerT.LINKID=TREAT.LINKID) AND TREAT.DISDATE IS NOT NULL THEN TREAT.DISDATE
				ELSE (SELECT FIRST 1 innerT.TRANSFER_DATE FROM TRANSFER innerT WHERE innerT.LINKID=TRANS.LINKID AND innerT.TRANSFER_NO=TRANS.TRANSFER_NO+1)
			END AS DATE) AS EventEndDate,
			CASE
				WHEN TRANS.TRANSFER_NO = (SELECT MAX(TRANSFER_NO) FROM TRANSFER innerT WHERE innerT.LINKID=TRANS.LINKID) THEN 
					CASE
						WHEN TREAT.DISDATE IS NULL THEN NULL
						WHEN TRIM(TREAT.LEAVING_TIME)='':'' THEN ''00:00''
						WHEN TREAT.LEAVING_TIME IS NULL THEN ''00:00''
						WHEN TRIM(TREAT.LEAVING_TIME)='''' THEN ''00:00''
						ELSE SUBSTRING(TREAT.LEAVING_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TREAT.LEAVING_TIME FROM 3 FOR 2) 
					END
				ELSE (
						SELECT FIRST 1
							CASE
								WHEN innerT.TRANSFER_DATE IS NULL THEN NULL
								WHEN TRIM(innerT.TRANSFER_TIME)='':'' THEN ''00:00''
								WHEN innerT.TRANSFER_TIME IS NULL THEN ''00:00''
								WHEN TRIM(innerT.TRANSFER_TIME)='''' THEN ''00:00''
								ELSE SUBSTRING(innerT.TRANSFER_TIME FROM 1 FOR 2)||'':''||SUBSTRING(innerT.TRANSFER_TIME FROM 3 FOR 2) 
							END
						FROM TRANSFER innerT WHERE innerT.LINKID=TRANS.LINKID AND innerT.TRANSFER_NO=TRANS.TRANSFER_NO+1
				) 
			END AS EventEndTime,  
			TRANS.TRANSFER_CONS AS Consultant,
			TRANS.TRANSFER_WARD AS Ward,
			TRANS.TRANSFER_SPEC AS Specialty,
			CASE
				WHEN TRANS.TRANSFER_NO = (SELECT MAX(TRANSFER_NO) FROM TRANSFER innerT WHERE innerT.LINKID=TREAT.LINKID) AND TREAT.DISDATE IS NOT NULL THEN ''D''
				ELSE ''T'' 
			END AS Type
		FROM
			TRANSFER TRANS
			INNER JOIN TREATMNT TREAT ON TRANS.LINKID=TREAT.LINKID
		WHERE
			TREAT.TRT_DATE BETWEEN '''+@StartDate+''' AND '''+@EndDate+''' AND
			SUBSTRING(TREAT.TRT_TYPE FROM 1 FOR 1)=''A''
UNION ALL
		SELECT 
			''East'' AS Area,
			''Myrddin'' AS Source,
			TREAT.CASENO AS LocalPatientIdentifier,
			TREAT.LINKID AS SpellNumber,
			0 AS TransferNumber,
			0 AS EpisodeNumber,
			CAST(TREAT.TRT_DATE AS DATE) AS EventStartDate,
			CASE
				WHEN TREAT.TRT_DATE IS NULL THEN NULL
				WHEN TRIM(TREAT.APPOINTMENT_TIME)='':'' THEN ''00:00''
				WHEN TREAT.APPOINTMENT_TIME IS NULL THEN ''00:00''
				WHEN TRIM(TREAT.APPOINTMENT_TIME)='''' THEN ''00:00''
				ELSE SUBSTRING(TREAT.APPOINTMENT_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TREAT.APPOINTMENT_TIME FROM 3 FOR 2) 
			END AS EventStartTime,
			CAST(COALESCE(TRANS.TRANSFER_DATE,TREAT.DISDATE) AS DATE) AS EventEndDate,
			COALESCE(
				CASE
					WHEN TRANS.TRANSFER_DATE IS NULL THEN NULL
					WHEN TRIM(TRANS.TRANSFER_TIME)='':'' THEN ''00:00''
					WHEN TRANS.TRANSFER_TIME IS NULL THEN ''00:00''
					WHEN TRIM(TRANS.TRANSFER_TIME)='''' THEN ''00:00''
					ELSE SUBSTRING(TRANS.TRANSFER_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TRANS.TRANSFER_TIME FROM 3 FOR 2) 
				END,
				CASE
					WHEN TREAT.DISDATE IS NULL THEN NULL
					WHEN TRIM(TREAT.LEAVING_TIME)='':'' THEN ''00:00''
					WHEN TREAT.LEAVING_TIME IS NULL THEN ''00:00''
					WHEN TRIM(TREAT.LEAVING_TIME)='''' THEN ''00:00''
					ELSE SUBSTRING(TREAT.LEAVING_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TREAT.LEAVING_TIME FROM 3 FOR 2) 
				END
			) AS EventEndTime,
			TREAT.ACONS AS Consultant,
			TREAT.ALOC AS Ward,
			TREAT.ASPEC AS Specialty,
			''A'' AS Type
		FROM
			TREATMNT TREAT
			LEFT JOIN TRANSFER TRANS ON TRANS.LINKID=TREAT.LINKID AND TRANS.TRANSFER_NO=1
		WHERE
			TREAT.TRT_DATE BETWEEN '''+@StartDate+''' AND '''+@EndDate+''' AND
			SUBSTRING(TREAT.TRT_TYPE FROM 1 FOR 1)=''A''
	) 
		ORDER BY 
			SpellNumber,
			TransferNumber'
) AT [WPAS_EAST];

END

GO
