SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[Get_PAS_Data_WardTransferCentral]
	
AS
BEGIN
	
	SET NOCOUNT ON;

	
   	DECLARE @StartDate AS DATE = CAST((SELECT ISNULL(MAX(EventStartDate),'1 JANUARY 2015') FROM [Foundation].[dbo].[PAS_Data_WardTransfer] WHERE Type='A' AND Area='Central') AS DATE)
	DECLARE @EndDate AS VARCHAR(30) = DATENAME(DAY,GETDATE()) + ' ' + DATENAME(MONTH,GETDATE()) + ' ' + DATENAME(YEAR,GETDATE())

--DECLARE @StartDate AS DATE = '1 APRIL 2015'
--DECLARE @EndDate AS DATE = CAST(GETDATE() AS DATE)--'30 APRIL 2018'

EXEC('
	SELECT * FROM(
		SELECT 
			''Central'' AS Area,
			''WPAS'' AS Source,
			TREAT.CASENO AS LocalPatientIdentifier,
			TRANS.LINKID AS SpellNumber,
			TRANS.TRANSFER_NO AS TransferNumber,
			TRANS.EPISODENO AS EpisodeNumber,
			CAST(TRANS.TRANSFER_DATE AS DATE) AS EventStartDate,
			CASE
				WHEN TRANS.TRANSFER_DATE IS NULL THEN NULL
				WHEN NULLIF(TRIM(REPLACE(TRANS.TRANSFER_TIME,'':'','''')),'''') IS NULL THEN ''00:00''
				ELSE SUBSTRING(TRANS.TRANSFER_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TRANS.TRANSFER_TIME FROM 3 FOR 2) 
			END AS EventStartTime,
			CAST(CASE
				WHEN TRANS.TRANSFER_NO = (SELECT MAX(TRANSFER_NO) FROM TRANSFER innerT WHERE innerT.LINKID=TREAT.LINKID) AND TREAT.DISDATE IS NOT NULL THEN TREAT.DISDATE
				ELSE (SELECT FIRST 1 innerT.TRANSFER_DATE FROM TRANSFER innerT WHERE innerT.LINKID=TRANS.LINKID AND innerT.TRANSFER_NO=TRANS.TRANSFER_NO+1) --Had to add FIRST 1 as, believe it or not, there are repeated transfer numbers for 45 linkid''s (at the time of checking)
			END AS DATE) AS EventEndDate,
			CASE
				WHEN TRANS.TRANSFER_NO = (SELECT MAX(TRANSFER_NO) FROM TRANSFER innerT WHERE innerT.LINKID=TRANS.LINKID) THEN 
					CASE
						WHEN TREAT.DISDATE IS NULL THEN NULL
						WHEN NULLIF(TRIM(REPLACE(TREAT.LEAVING_TIME,'':'','''')),'''') IS NULL THEN ''00:00''
						ELSE SUBSTRING(TREAT.LEAVING_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TREAT.LEAVING_TIME FROM 3 FOR 2) 
					END
				ELSE (
						SELECT FIRST 1
							CASE
								WHEN innerT.TRANSFER_DATE IS NULL THEN NULL
								WHEN NULLIF(TRIM(REPLACE(innerT.TRANSFER_TIME,'':'','''')),'''') IS NULL THEN ''00:00''
								ELSE SUBSTRING(innerT.TRANSFER_TIME FROM 1 FOR 2)||'':''||SUBSTRING(innerT.TRANSFER_TIME FROM 3 FOR 2) 
							END
						FROM TRANSFER innerT WHERE innerT.LINKID=TRANS.LINKID AND innerT.TRANSFER_NO=TRANS.TRANSFER_NO+1
				) 
			END AS EventEndTime,  
			TRANS.TRANSFER_CONS AS Consultant,
			TRANS.TRANSFER_WARD AS Ward,
			TRANS.TRANSFER_SPEC AS Specialty,
			CASE
				WHEN TRANS.TRANSFER_NO = (SELECT MAX(TRANSFER_NO) FROM TRANSFER innerT WHERE innerT.LINKID=TREAT.LINKID) AND TREAT.DISDATE IS NOT NULL THEN ''D''
				ELSE ''T'' 
			END AS Type
		FROM
			TRANSFER TRANS
			INNER JOIN TREATMNT TREAT ON TRANS.LINKID=TREAT.LINKID
		WHERE
			TREAT.TRT_DATE BETWEEN '''+@StartDate+''' AND '''+@EndDate+''' AND
			LEFT(TREAT.TRT_TYPE,1)=''A'' --THERE ARE 3 ENTRIES IN TRANSFERS THAT LINK BACK TO OA ENTRIES IN THE TREATMNT TABLE
			--LEFT(TREAT.LINKID,1)=''M'' 
UNION ALL
		SELECT 
			''Central'' AS Area,
			''WPAS'' AS Source,
			TREAT.CASENO AS LocalPatientIdentifier,
			TREAT.LINKID AS SpellNumber,
			0 AS TransferNumber,
			0 AS EpisodeNumber,
			CAST(TREAT.TRT_DATE AS DATE) AS EventStartDate,
			CASE
				WHEN TREAT.TRT_DATE IS NULL THEN NULL
				WHEN NULLIF(TRIM(REPLACE(TREAT.APPOINTMENT_TIME,'':'','''')),'''') IS NULL THEN ''00:00''
				ELSE SUBSTRING(TREAT.APPOINTMENT_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TREAT.APPOINTMENT_TIME FROM 3 FOR 2) 
			END AS EventStartTime,
			CAST(COALESCE(TRANS.TRANSFER_DATE,TREAT.DISDATE) AS DATE) AS EventEndDate,
			COALESCE(
				CASE
					WHEN TRANS.TRANSFER_DATE IS NULL THEN NULL
					WHEN NULLIF(TRIM(REPLACE(TRANS.TRANSFER_TIME,'':'','''')),'''') IS NULL THEN ''00:00''
					ELSE SUBSTRING(TRANS.TRANSFER_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TRANS.TRANSFER_TIME FROM 3 FOR 2) 
				END,
				CASE
					WHEN TREAT.DISDATE IS NULL THEN NULL
					WHEN NULLIF(TRIM(REPLACE(TREAT.LEAVING_TIME,'':'','''')),'''') IS NULL THEN ''00:00''
					ELSE SUBSTRING(TREAT.LEAVING_TIME FROM 1 FOR 2)||'':''||SUBSTRING(TREAT.LEAVING_TIME FROM 3 FOR 2) 
				END
			) AS EventEndTime,
			TREAT.ACONS AS Consultant,
			TREAT.ALOC AS Ward,
			TREAT.ASPEC AS Specialty,
			''A'' AS Type
		FROM
			TREATMNT TREAT
			LEFT JOIN TRANSFER TRANS ON TRANS.LINKID=TREAT.LINKID AND TRANS.TRANSFER_NO=1
		WHERE
			TREAT.TRT_DATE BETWEEN '''+@StartDate+''' AND '''+@EndDate+''' AND
			LEFT(TREAT.TRT_TYPE,1)=''A'' --AND
			--LEFT(T.LINKID,1)=''M''
--''M1000087869''
	) 
		ORDER BY 
			SpellNumber,
			TransferNumber'
) AT [WPAS_CENTRAL];

END

GO
