SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE PROCEDURE [dbo].[Get_Diagnostic_Ref_Patient]
	
AS
BEGIN
	
	SET NOCOUNT ON;

	/*
	exec [dbo].[Get_Diagnostic_Ref_Patient]
	*/


-- REMOVE AND REPLACE/RE-INSERT LAST 7 DAYS (HISTORIC) EVERY DAY APART FORM SUNDAY (30 DAYS REPLACED) TO MATCH NDR FEED REFRESH --
-- DW2 TABLE DOES NOT CURRENTLY INCLUDE TODAY'S DATA (YESTERDAY'S DATA ONWARDS HISTORICALLY) --

DELETE FROM [Foundation].[dbo].[Diagnostic_Ref_Patient] WHERE CAST([DateOfEntry] AS DATE) BETWEEN (CASE WHEN DATEPART(WEEKDAY, GETDATE()) = 1 THEN CAST(GETDATE() -30 AS DATE) ELSE CAST(GETDATE() -7 AS DATE) END) AND CAST(GETDATE() -1 AS DATE)

SELECT DISTINCT

	[LimsMdsId],
	[VisitNumber],
	[Surname],
	[Forename],
	[NHSNumber],
	[EPVIS_HospitalUR] AS [LocalPatientIdentifier],
	[Sex],
	[DoB],
	[Postcode],
	ISNULL([EPVIS_HospitalUR],'') + '|' + CAST([LimsMdsId] AS VARCHAR) + '|' + [HospitalCode] + '|LIMS|Diagnostic' AS [PatientLinkID],
	[DateofEntry]

FROM [7a1a1srvinfondr].[LIMS].[dbo].[LIMS_MDS] 

WHERE 1 = 1
-- (SUNDAY = 1) THIS IS TO DELETE & RE-INSERT LAST 30 DAYS EVERY SUNDAY --
-- OTHER DAYS TO DELETE & RE-INSERT LAST 7 DAYS --
AND CAST([DateOfEntry] AS DATE) BETWEEN (CASE WHEN DATEPART(WEEKDAY, GETDATE()) = 1 THEN CAST(GETDATE() -30 AS DATE) ELSE CAST(GETDATE() -7 AS DATE) END) AND CAST(GETDATE() -1 AS DATE)


END
GO
