SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[Get_PAS_Data_Waiters_Centralv222vBKD]
	
AS
BEGIN
	
	SET NOCOUNT ON;
	


--CAST(extract(month from current_timestamp) ||'/'||extract(day from current_timestamp)||'/'||extract(year from current_timestamp) as date) as SnapDate,
--cast(''Now'' as Date) as DateWaitingListCensus,

EXEC('
select  
       CAST(extract(month from current_timestamp) ||''/''||extract(day from current_timestamp)||''/''||extract(year from current_timestamp) as date) as SnapDate,
       TREATMNT_1.CASENO, PATHWAYMGT_1.UPI,
       TREATMNT_1.TRT_DATE, TREATMNT_1.ACONS, 
       TREATMNT_1.ASPEC, TREATMNT_1.ALOC, 
       TREATMNT_1.APPOINTMENT_TIME,
       patient.surname||'', ''||patient.forename as FULLNAME,
       PATHWAYMGT_1.EVENT_SOURCE, 
       PATHWAYMGT_1.EVENT_TYPE, 
       TREATMNT_1.TRT_TYPE, TREATMNT_1.SOURCE, 
       CONS_1.ALL_NAME, TREATMNT_1.LINKID, 
       TREATMNT_1.ACTNOTEKEY, PATIENT_1.TITLE, 
       PATIENT_1.SURNAME, PATIENT_1.FORENAME, 
       PATIENT_1.ADDRESS, PATIENT_1.POSTCODE, 
       PATIENT_1.TELEPHONE_DAY, 
       PATIENT_1.TELEPHONE_NIGHT, 
       PATIENT_1.MOBILENO, PATIENT_1.BIRTHDATE, 
       PATIENT_1.SEX, PATIENT_1.NHS, 
       PATIENT_1.REGISTERED_GP, GP2_1.GP_NAME, 
       PATIENT_1.GP_PRACTICE, GP2_1.ADDR, 
       PATIENT_1.DHA_CODE,
       GP2_1.GP_CODE,
       TREATMNT_1.GPREFNO, 
       TREATMNT_1.CREATE_USER,
       TREATMNT_1.CREATE_DATE,
       TREATMNT_1.LAST_MODIFY_USER,
       TREATMNT_1.LAST_MODIFY_DATE,
       TREATMNT_1.OTHER_INFO,
       TREATMNT_2.TRT_DATE TRT_DATE_2, 
       TREATMNT_2.OUTCOME, 
       TREATMNT_2.NEXT_APPROX_APPT,
       TREATMNT_2.NEXT_APPT_CONS,
       TREATMNT_2.NEXT_APPT_SPEC,
       TREATMNT_2.NEXT_APPT_LOC,
       TREATMNT_2.NEXT_CLIN_CON
FROM TREATMNT TREATMNT_1
      LEFT OUTER JOIN PATIENT PATIENT_1 ON 
     (PATIENT_1.CASENO = TREATMNT_1.CASENO)
      LEFT OUTER JOIN PATHWAYMGT PATHWAYMGT_1 ON 
     (PATHWAYMGT_1.ACTNOTEKEY = TREATMNT_1.ACTNOTEKEY)
      LEFT OUTER JOIN CONS CONS_1 ON 
     (CONS_1.CONSULTANT_INITIALS = TREATMNT_1.ACONS)
      AND (CONS_1.CONSULTANT_SPECIALTY = TREATMNT_1.ASPEC)
      LEFT OUTER JOIN GP2 GP2_1 ON 
     (GP2_1.GP_CODE = PATIENT_1.REGISTERED_GP)
      AND (GP2_1.PRACTICE = PATIENT_1.GP_PRACTICE)
      LEFT OUTER JOIN TREATMNT TREATMNT_2 ON 
     (TREATMNT_2.CASENO = TREATMNT_1.CASENO)
      AND (TREATMNT_2.LINKID = TREATMNT_1.LINKID)
      AND TREATMNT_2.ACTNOTEKEY = (SELECT FIRST 1 TRT3.ACTNOTEKEY
                        FROM TREATMNT TRT3
                        WHERE TRT3.LINKID = TREATMNT_1.LINKID
                        AND TRT3.CASENO = TREATMNT_1.CASENO
       AND ( TRT3.TRT_DATE < CURRENT_TIMESTAMP )
       AND ( TRT3.OUTCOME NOT LIKE ''9%'' )
       ORDER by TRT3.TRT_DATE desc
)
WHERE 
      ( TREATMNT_1.TRT_DATE >= current_timestamp)
       AND ( TREATMNT_1.TRT_TYPE = ''OT'' )
       AND ( TREATMNT_1.SOURCE <> ''21'')
       AND ( PATHWAYMGT_1.EVENT_SOURCE <> ''MT'' )

'
) at [WPAS_Central];
END



GO
