SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE Procedure  [dbo].[Get_Datix_Data_Concern] as begin 

SELECT DISTINCT
NULLIF(recordid,'') as RecordID
,NULLIF(updateid,'') as UpdateID
--,NULLIF(com_name,'') as ComplainantName
,NULLIF(com_mgr,'') as Handler
,NULLIF(com_ourref,'') as BCURefId
,NULLIF(com_unit,'') as PrimarySite
,NULLIF(com_otherref,'') as SecondaryReference
,NULLIF(com_type,'') as CommunicationType
,NULLIF(com_subtype,'') as SubType
,NULLIF(com_outcome,'') as PrimaryOutcome
,NULLIF(com_method,'') as CommunicationMethod
,NULLIF(com_purchaser,'') as ConcernGrade
,NULLIF(CONVERT(date,com_dincident),'') as IncidentDate
,NULLIF(CONVERT(date,com_dreceived),'') as ReceivedDate
,NULLIF(CONVERT(date,com_dclosed),'') as ClosedDate
,NULLIF(CONVERT(date,com_dreopened),'') as ReopenedDate
,NULLIF(com_curstage,'') as CurrentStage
,NULLIF(com_head,'') as Manager
,NULLIF(com_directorate,'') as PrimaryDirectorate
,NULLIF(com_specialty,'') as PrimarySpecialty
,NULLIF(com_drequest,'') as Request
,NULLIF(com_ddueackreq,'') as DueACkReq
,NULLIF(com_dackreq,'') as DackReq
,NULLIF(com_dstatement,'') as [Statement]
,NULLIF(com_dduedecision,'') as DueDecision
,NULLIF(com_ddecision,'') as Decision
,NULLIF(com_recir,'') as RecIR
,NULLIF(com_dinform,'') as InformedDate
,NULLIF(com_dduepappt,'') as DueAppt
,NULLIF(com_dpappt,'') as Appt
,NULLIF(com_dduepdraft,'') as DueDraft
,NULLIF(com_dpdraft,'') as Draft
,NULLIF(com_ddueppublish,'') as DuePublish
,NULLIF(com_dppublish,'') as Publish
,NULLIF(com_dduecereply,'') as DueCeReply
,NULLIF(com_dcereply,'') as Reply
,com_expenses as Expenses
,NULLIF(com_koservarea,'') as KoServArea
,NULLIF(com_kosubject,'') as KoSubject
,NULLIF(com_koprof,'') as KoProf
,NULLIF(com_subject1,'') as [Subject]
,NULLIF(com_subsubject1,'') as SubSubject
,NULLIF(com_location1,'') as SecondaryLocationActual
,NULLIF(com_directorate1,'') as SecondaryDirectorate
,NULLIF(com_stafftype1,'') as StaffType
,NULLIF(com_specialty1,'') as SecondarySpecialty
,NULLIF(seclevel,'') as SecLevel
,NULLIF(secgroup,'') as SecGroup
,NULLIF(CONVERT(date,updateddate),'') as UpdatedDate
,NULLIF(CONVERT(varchar(20),updatedby),'') as UpdatedBy
,NULLIF(com_dduelaychair,'') as DueLayChair
,NULLIF(com_dlaychair,'') as LayChair
,NULLIF(com_ircode,'') as IRCode
,NULLIF(com_assessor,'') as Assessor
,NULLIF(com_koethnic_pat,'') as KoEthnicPatient
,NULLIF(com_koethnic_staff,'') as KoEthnicStaff
,NULLIF(com_consent,'') as Consent
,NULLIF(com_outcome1,'') as SecondaryOutcome
,NULLIF(com_ko41_type,'') as Ko41Type
,NULLIF(com_organisation,'') as PrimaryOrganisation
,NULLIF(com_clingroup,'') as ClinicalGroup
,NULLIF(com_investigator,'') as Investigator
,NULLIF(CONVERT(date,com_inv_dstart),'') as InvestigationStartDate
,NULLIF(CONVERT(date,com_inv_dcomp),'') as InvestigationCompleteDate
,NULLIF(com_impact,'') as Impact
,NULLIF(com_consequence,'') as Consequence
,NULLIF(com_likelihood,'') as Likelihood
,NULLIF(com_rating,'') as Rating
,NULLIF(com_grade,'') as Grade
,NULLIF(com_colour,'') as Colour
,NULLIF(com_root_causes,'') as RootCause
,NULLIF(com_inv_outcome,'') as InvestigationOutcome
,NULLIF(com_recomm_code,'') as RecommendCode
,NULLIF(com_action_code,'') as ActionCode
,NULLIF(com_lessons_code,'') as LessonsCode
,NULLIF(com_unit_type,'') as SiteType
,NULLIF(com_loctype,'') as PrimaryLocationType
,NULLIF(com_locactual,'') as PrimaryLocationActual
,NULLIF(com_inc_type,'') as IncidentType
,NULLIF(com_inc_category,'') as IncidentCategory
,NULLIF(com_inc_subcat,'') as IncidentSubCategory
,NULLIF(CONVERT(date,com_dopened),'') as OpenedDate
,NULLIF(com_clingroup1,'') as SecondaryClinicalGroup
,NULLIF(com_organisation1,'') as SecondaryOrganisation
,NULLIF(com_loctype1,'') as SecondaryLocationType
,NULLIF(com_unit1,'') as SecondarySite
,NULLIF(com_ddueinform,'') as DueInform
,weighting as Weighting
,NULLIF(com_isd_unit,'') as ISDUnit
,NULLIF(com_isd_locactual,'') as ISDLocationActual
,NULLIF(com_isd_consent,'') as ISDConsent
,NULLIF(com_isd_dconsent_req,'') as ISDConsentReq
,NULLIF(com_isd_dconsent_rec,'') as ISDConsentRec
,NULLIF(com_isd_div_sent,'') as ISDDivSent
,NULLIF(com_isd_ref_added,'') as ISDRefAdded
,NULLIF(com_isd_iaas_involved,'') as ISDIAASInvolved
,NULLIF(com_isd_cas_involved,'') as ISDCasInvolved
,NULLIF(com_isd_chi_no,'') as ISDChiNo
,NULLIF(com_isd_resp_sent_20,'') as ISDRespSent20
,NULLIF(com_isd_resp_20_reason,'') as ISDResp20Reason
,NULLIF(com_isd_agree_40,'') as ISDAgree40
,NULLIF(com_isd_agree_40_date,'') as ISDAgree40Date
,NULLIF(com_isd_actions,'') as ISDActions
,NULLIF(com_isd_dexport,'') as ISDExport
,NULLIF(rep_approved,'') as RepApproved
,NULLIF(submit_login,'') as SubmitLogin
,NULLIF(CONVERT(varchar(20),createdby),'') as CreatedBy
,NULLIF(show_person,'') as ShowPerson
,NULLIF(CONVERT(date,com_dcompleted1),'') as CompletedDate
--,NULLIF(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(COM_DETAIL, CHAR(9), ' '), CHAR(13), ' '), CHAR(10), ' '))),'') as ConcernDetails
,NULLIF(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(COM_SUMMARY, CHAR(9), ' '), CHAR(13), ' '), CHAR(10), ' '))),'') as Summary
,NULLIF(COM_REASON,'') as Reason
,NULLIF(COM_REPORT,'') as Report
,NULLIF(COM_IRSYNOPSIS,'') as IRSynopsis
,NULLIF(com_recommend,'') as Recommend
,NULLIF(com_inv_action,'') as InvestigationAction
,NULLIF(com_inv_lessons,'') as InvestigationLessons
,NULLIF(com_isd_resp_40_reason,'') as ISDResp40Reason
,NULLIF(com_isd_plan,'') as ISDPlan
,NULLIF(LEFT(REPLACE(REPLACE(CONVERT(VARCHAR(8000),LTRIM(RTRIM(com_notes1))),CHAR(13),''), CHAR(10),''),8000), '')
,NULLIF(com_type_tier_one,'') as TypeTier1
,NULLIF(com_type_tier_two,'') as TypeTier2
,NULLIF(com_type_tier_three,'') as TypeTier3
,NULLIF(com_affecting_tier_zero,'') as AffectingTierZero
,getdate() as LastUpdated
,'Datix' as [Source]

FROM [7a1ausrvdtxsql2].[Datixcrm].[dbo].[compl_main] m
 
 END
GO
